image: node:16.15.0

pages:
  cache:
    paths:
      - node_modules
  script:
    - npm install -g pug-cli
    - pug template -o src --pretty
    - npm install
    - npm run build
    - mv dist public
    - cp public/homepage.html public/index.html
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
