export default
[
    {
    "TYP": "3",
    "AduName": "奧萬大自然教育中心",
    "NAduName": "鳳凰花開時【畢業特別企劃】",
    "NAduType": "5",
    "onAskStart": "2022/01/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=AWD-SE1101",
    "ActDesc": "在驪歌響起時，想用一場特別的畢業旅行在回憶上添些色彩嗎？那一定別錯過我們特別為您量身打造的旅程！暫時告別電腦和遊樂器的虛擬世界，體驗一下真實的森林冒險和生態探索吧~別再考慮啦~名額有限喔！",
    "ActObject": null,
    "ActTime": null,
    "ActHours": null,
    "JoinDesc": "一般大眾",
    "JoinFee": "逕洽本中心"
    },
    {
    "TYP": "3",
    "AduName": "奧萬大自然教育中心",
    "NAduName": "森林探險家",
    "NAduType": "5",
    "onAskStart": "2022/01/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=AWD-SE1102",
    "ActDesc": "奧萬大的森林有著最安全，最適合孩子進行探索的環境。在森林中進行定向運動、生態觀察、看星星、觀鳥賞蛙、健行至吊橋等活動一應俱全，讓孩子在自然環境中學習獨立自主與培養團隊合作能力，奧萬大自然教育中心能帶給孩子一場獨特的森林冒險體驗喔！",
    "ActObject": null,
    "ActTime": null,
    "ActHours": null,
    "JoinDesc": "一般大眾",
    "JoinFee": "逕洽本中心"
    },
    {
    "TYP": "3",
    "AduName": "奧萬大自然教育中心",
    "NAduName": "漫步綠森林",
    "NAduType": "5",
    "onAskStart": "2022/01/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=AWD-SE1103",
    "ActDesc": " 最近有覺得身體有點緊繃嗎？想要好好沉澱一下自己嗎？奧萬大\r\n園區有著中海拔獨特的森林環境，藉由涼爽宜人溫度、富含芬多精的森林步道\r\n與瀑布區的負離子，幫您規劃一場專屬的森林療癒活動，讓身心靈都可以得到\r\n適當的舒緩。心動了嗎？趕快規劃一場屬於您的森林療癒之旅吧！",
    "ActObject": null,
    "ActTime": null,
    "ActHours": null,
    "JoinDesc": "一般大眾",
    "JoinFee": "逕洽本中心"
    },
    {
    "TYP": "3",
    "AduName": "奧萬大自然教育中心",
    "NAduName": "「親手接觸，向下扎根」–初探自然教育中心",
    "NAduType": "3",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=AWD-T1102",
    "ActDesc": "世界各國為了滿足自然保育兼具環境教育的功能，成立了許多的自然中心。林務局希望將與自然契合的場域，以永續發展的原則，結合有趣的課程和專業的人力，來提供民眾親近、瞭解、欣賞與愛護生態環境的機會，傳遞保育觀念，於是自2007年起陸續成立自然教育中心。奧萬大自然教育中心將告訴您林務局自然教育中心的發展，與奧萬大自然教育中心的特色、課程及所能提供的服務，並安排課程體驗，讓更多人瞭解自然教育中心。",
    "ActObject": "認識林務局自然教育中心，瞭解自然中心可以提供的服務，體驗自然教育中心豐富有趣的活動。",
    "ActTime": null,
    "ActHours": null,
    "JoinDesc": null,
    "JoinFee": "逕洽本中心"
    },
    {
    "TYP": "3",
    "AduName": "奧萬大自然教育中心",
    "NAduName": "「小達爾文的自然探索」工作坊",
    "NAduType": "3",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=AWD-T1103",
    "ActDesc": "英國田野研究協會(Field\r\nStudies Council；FSC)成立於1943年，目標是讓大眾了解「環境」的概念。透過所謂「戶外教室」(outdoor classroom)的課程，實際和環境接觸，進而學習；奧萬大自然教育中心將透過FSC「小達爾文的冒險旅程」一書來引導課程操作，讓學員實際和環境接觸，進而發現、學習並且親身體驗活動，來瞭解各種環境調查的方式並習得調查的技巧。",
    "ActObject": "永續發展自然教育與戶外學習、學生在教室以外的啟發式學習和培養科學的邏輯思考及團隊合作的精神。",
    "ActTime": null,
    "ActHours": null,
    "JoinDesc": "機關團體、一般大眾",
    "JoinFee": "逕洽本中心"
    },
    {
    "TYP": "3",
    "AduName": "奧萬大自然教育中心",
    "NAduName": "「LNT－無痕山林」工作坊",
    "NAduType": "3",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=AWD-T1104",
    "ActDesc": "無痕山林運動（Leave\r\nNo Trace；LNT）源自於美國無痕旅遊運動，主要肇因於1960年代美國大眾旅遊對環境的嚴重衝擊。LNT旨在提醒人們對於所處的山林環境善盡應有的關懷與責任，以減少衝擊的活動方式和行為，達成親近山林的體驗。奧萬大自然教育中心將利用林務局之「無痕山林」運動執行委員會所編訂的教育宣導手冊，搭配LNT種子教師與規劃的新課程讓民眾對登山活動擁有全新的觀點與熱情。",
    "ActObject": "了解如何培養愛山林、愛自然的積極知識與態度；體驗全新、不同以往的登山經驗；獲得「無痕山林」運動的七大準則與行動概念。",
    "ActTime": null,
    "ActHours": null,
    "JoinDesc": "機關團體、一般大眾",
    "JoinFee": "逕洽本中心"
    },
    {
    "TYP": "3",
    "AduName": "奧萬大自然教育中心",
    "NAduName": "「環境教育課程」研習",
    "NAduType": "3",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=AWD-T1105",
    "ActDesc": "環境教育是1960年代中期興起的學門，而聯合國人類環境會議於1972年發表人類宣言，會中提出「發展環境教育是解決環境問題最佳策略之一」的見解，於1992年的地球高峰會提出了21世紀議程後，環境教育成為了世界公民必備的通識。我國於1983年推動環境教育立法，於2011年正式實行。本中心不僅具備良好的天然環境，並有許多不同類型的環境教育課程，可依參與者背景與需求調整，透過中心多樣化的環境教育課程，期能帶領更多人投入環境教育，成為負責任的世界公民。",
    "ActObject": "透過認識環境教育的概念與理論、環境教育活動的體驗與教學，培育更多環境教育的種子教師。",
    "ActTime": null,
    "ActHours": null,
    "JoinDesc": "機關團體、一般大眾",
    "JoinFee": "逕洽本中心"
    },
    {
    "TYP": "3",
    "AduName": "奧萬大自然教育中心",
    "NAduName": "「森林與環境教育」系列研習",
    "NAduType": "3",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=AWD-T1106",
    "ActDesc": "森林生物多樣性可能是所有陸域系統中最豐富的，為了讓民眾能夠更瞭解奧萬大環境中豐富的生物資源及要如何永續利用森林資源，本中心開辦「森林與環境教育」系列研習，內容包括了動、植物專題及森林療癒，還有更多精彩主題會陸續推出，歡迎有興趣的民眾鎖定中心消息及報名。",
    "ActObject": "探索奧萬大森林，學習與其他生物和平共處，宣導環境教育觀念。",
    "ActTime": null,
    "ActHours": null,
    "JoinDesc": "機關團體、一般大眾",
    "JoinFee": "逕洽本中心"
    },
    {
    "TYP": "3",
    "AduName": "八仙山自然教育中心",
    "NAduName": "Bio-go繽紛",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=BSS-SP1110",
    "ActDesc": "帶學員至八仙山自然教育中心進行戶外教學，以生物多樣性為學習主軸，透過遊戲、闖關、自然觀察，讓學生在森林中，發現生物多樣性的奧秘，學習與自然互動方式，並學習愛護自然環境。",
    "ActObject": "1.觀察森林日、夜間的生物。\r\n2.體驗八仙山之美。\r\n3.認識生物多樣性的意涵。\r\n4.了解保育生物多樣性的重要，學會尊重人與自然。\r\n5.培養解決問題與團隊合作的能力。\r\n",
    "ActTime": "1.活動為兩天一夜\r\n2.最晚活動前一個月前向本中心提出申請",
    "ActHours": null,
    "JoinDesc": "學期中，學校老師帶學生進行戶外教學",
    "JoinFee": "每人 1300 元，含課程材料費、住宿、保險及點心"
    },
    {
    "TYP": "3",
    "AduName": "觸口自然教育中心",
    "NAduName": "植物探員",
    "NAduType": "2",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動0天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=CK-TA1101",
    "ActDesc": "7/9(六)09：00-11：30\t植物探員-入門挑戰\t\r\n科學家是如何將隨著季節凋零的葉子製作成可長時間保存及研究的臘葉標本呢?植物標本又可以帶給科學家哪些靈感?一起探索植物世界！\r\n\r\n7/16(六) \r\n09：00-11：30\t葉脈祕聞\t\r\n每棵樹都有葉子，每片葉子也都是獨一無二！在科學家眼裡，葉子可是樹的身份證呢！\r\n\r\n7/23(六) 09：00-11：30\t你榕我榕一起榕\t\r\n台灣有一群獨特的榕屬植物，他們可能住在學校的操場，也是廟宇的守護神！在大自然中他們與一群小小的昆蟲共譜瞭活潑有趣的生之歌，快來拜訪他們吧！\r\n\r\n7/30(六)09：00-11：30\t植物探員-成就達成\t\r\n利用前幾周親手準備的材料，製作出美麗自己的第一份臘葉標本！將大自然的美麗好好保存吧！\r\n\r\n",
    "ActObject": "1.瞭解植物的微觀世界及有趣之處。\r\n2.認識榕果小蜂與榕屬植物間的神祕關係，並理解其生態意涵。\r\n3.實際體驗及瞭解標本的採集倫理及標本製作該有的科學素養。\r\n4.進行科學繪圖及臘葉標本製作，並瞭解科學繪圖與標本的關係。\r\n5.利用大自然素材創作紀念品，體會大自然的美好。",
    "ActTime": "請從中心臉書專頁公告之報名連結上網報名　　\r\n報名網址：https://forms.gle/th8qY2FBEhuGo9Dt6\r\n7/9(六)09:00-11:30 ,\r\n7/16(六) 09:00-11:30\r\n7/23(六) 09:00-11:30 ,\r\n7/30(六)09:00-11:30\r\n",
    "ActHours": null,
    "JoinDesc": "3~8年級親子 ",
    "JoinFee": "4堂優惠：900元/人、單堂250元/人"
    },
    {
    "TYP": "3",
    "AduName": "池南自然教育中心",
    "NAduName": "環境教育特製方案",
    "NAduType": "5",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動10天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=CN-SE1101",
    "ActDesc": "針對團體的學習旅行、校外教學需求，提供客製化服務，我們將依團體人數，設計環境教育解說及生態大地遊戲系列活動，讓參與者能從遊戲中體驗生態保育的觀念。",
    "ActObject": null,
    "ActTime": "週一～週五為主",
    "ActHours": null,
    "JoinDesc": "學校、機關、公私立團體",
    "JoinFee": "請來電洽詢 03-8641594#15 石斑魚老師"
    },
    {
    "TYP": "3",
    "AduName": "池南自然教育中心",
    "NAduName": "森林之夜",
    "NAduType": "5",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動14天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=CN-SE1102",
    "ActDesc": "池南森林的夜晚充滿許多秘密，有發光的小精靈(螢火蟲4-5月限定)、夏夜羽化的蟬、唱著情歌的蛙、演奏著樂器的鳴蟲及遠遠傳來黃嘴角鴞叫聲，邀請您一起來體驗屬於池南的夜晚。",
    "ActObject": null,
    "ActTime": "課程時間：18:30-20:30\r\n請洽(03)864-1594＃15 教育推廣組",
    "ActHours": null,
    "JoinDesc": "學校、機關、公私立團體",
    "JoinFee": "200元/人（不含入園門票、晚餐）。"
    },
    {
    "TYP": "3",
    "AduName": "池南自然教育中心",
    "NAduName": "森林尋寶趣",
    "NAduType": "5",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動14天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=CN-SE1103",
    "ActDesc": "沒有Google地圖及手機定位要怎麼找到目的地呢？來認識定向運動，一起練習判讀地圖及使用指北針，尋找池南森林裡的寶藏吧！",
    "ActObject": null,
    "ActTime": null,
    "ActHours": null,
    "JoinDesc": "學校、機關、公私立團體",
    "JoinFee": "100元/人(不含入園門票)"
    },
    {
    "TYP": "3",
    "AduName": "池南自然教育中心",
    "NAduName": "環境教育特製方案-親子溯溪體驗",
    "NAduType": "5",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=CN-SE1104",
    "ActDesc": "這是孩子們展現活力的時刻，邀請大小朋友與我們走入海岸山脈溪流祕境，回溯蜿蜒十二號橋水域，嬉遊於在沁涼的溪水中，親子共同體驗溪流生態的多樣性。中心期盼連結學員與土地的情感，創造美好的童年回憶，盡情享受難得的夏日消暑時光。",
    "ActObject": null,
    "ActTime": "活動約3-4小時",
    "ActHours": null,
    "JoinDesc": "6歲以上親子，團體20-40人",
    "JoinFee": "每人 400 元(含保險、小點心及課程費)"
    },
    {
    "TYP": "3",
    "AduName": "池南自然教育中心",
    "NAduName": "環境教育特製方案-【國產的材好】木工體驗",
    "NAduType": "5",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=CN-SE1105",
    "ActDesc": "認識國產材，親手將溫潤的木頭加工，由專業的木工師傅手把手帶領進入木工的領域，親自將木材製成實用的生活用品，讓美好的木作產品提升居家生活品質。",
    "ActObject": null,
    "ActTime": "3小時",
    "ActHours": null,
    "JoinDesc": "18歲以上成人",
    "JoinFee": "600~1,000元 /人 (依木作產品差異收費)"
    },
    {
    "TYP": "3",
    "AduName": "池南自然教育中心",
    "NAduName": "環境教育特製方案-【春夏限定】童年時光機",
    "NAduType": "5",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=CN-SE1107",
    "ActDesc": "帶領學員走訪光復野菜市場，感受原住民文化的禮讚，漫步在沁涼的幸福湧泉溪，盡情享受難得的夏日消暑美好時光，讓笑聲迴盪在迷人的田園風光，品嘗土地所饋予的豐盛餐點，中心期盼連結學員與土地的情感，創造美好的童年回憶。",
    "ActObject": null,
    "ActTime": "4小時(含午餐)",
    "ActHours": null,
    "JoinDesc": null,
    "JoinFee": "650元 /人 (依活動內容調整收費)"
    },
    {
    "TYP": "3",
    "AduName": "池南自然教育中心",
    "NAduName": "環境教育特製方案-森林療育",
    "NAduType": "5",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=CN-SE1108",
    "ActDesc": "運用各種自然元素，在創作中與自己的內在溝通。\r\n讓自己享受在森林裡的感覺，透過活動的引導，感受森林帶來的魅力。\r\n你會發現自己的成長，在森林裡。",
    "ActObject": null,
    "ActTime": "3小時",
    "ActHours": null,
    "JoinDesc": null,
    "JoinFee": "300~500元 /人 (依活動內容調整收費)"
    },
    {
    "TYP": "3",
    "AduName": "池南自然教育中心",
    "NAduName": "鳥兒甜蜜的家",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=CN-SP1101",
    "ActDesc": "鳥爸爸、鳥媽媽迎接鳥寶寶的誕生，佈置一個甜蜜的家，在親鳥細心呵護下，期盼小小鳥能夠在安全的環境順利長大。而鳥兒們的平時生活有哪些有趣的事，又面臨哪些壓力？讓我們透過課程活動一同來探索。",
    "ActObject": "1. 瞭解鳥類的生態習性及育雛的過程\r\n2. 感受鳥類生存所受到的壓力來源\r\n3. 思考日常行為對於鳥類生存的影響",
    "ActTime": "星期一至星期五，於學期間接受申請。",
    "ActHours": null,
    "JoinDesc": "幼兒園",
    "JoinFee": "學生：30元(門票10元、課程費20元)教師及家長：園區門票費"
    },
    {
    "TYP": "3",
    "AduName": "池南自然教育中心",
    "NAduName": "守護青蛙",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=CN-SP1102",
    "ActDesc": "近年來，森林遭受破壞、環境污染等問題，使得身為環境指標的青蛙，遭遇前所未有的衝擊。藉由課程的操作，我們一起來感受青蛙生存的挑戰與困境，並體會保護生態棲地的重要性。",
    "ActObject": "1. 瞭解青蛙生存的危機\r\n2. 探討人類行為對於青蛙的衝擊\r\n3. 尋求保護青蛙棲息環境的有效方法",
    "ActTime": "星期一至星期五，於學期間接受申請。",
    "ActHours": "5小時",
    "JoinDesc": "國小4～6年級",
    "JoinFee": "學生：30元(門票10元、課程費20元)教師及家長：園區門票費"
    },
    {
    "TYP": "3",
    "AduName": "池南自然教育中心",
    "NAduName": "森林棲地大作戰",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=CN-SP1103",
    "ActDesc": "由於棲息環境遭受人為破壞，台灣哺乳類動物數量日漸減少。透過體驗課程活動，我們一同認識台灣原生哺乳類動物的種類與習性，並思考牠們在台灣生存的困境。",
    "ActObject": "1. 瞭解台灣原生哺乳類動物的種類\r\n2. 體會生物與森林棲地的關聯性\r\n3. 思考原生哺乳類動物的生存困境",
    "ActTime": "星期一至星期五，於學期間接受申請。",
    "ActHours": "5小時",
    "JoinDesc": "國小4～6年級",
    "JoinFee": "學生：30元(門票10元、課程費20元)教師及家長：園區門票費。木頭DIY加價購，推廣價30元/人"
    },
    {
    "TYP": "3",
    "AduName": "池南自然教育中心",
    "NAduName": "鷹眼看大地",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=CN-SP1104",
    "ActDesc": "猛禽在生態平衡上扮演重要的角色，然而土地過度開發、環境污染等問題，使得猛禽生存面臨極大的威脅。邀您一同來瞭解猛禽的習性及生存危機，並探討人類行為對於猛禽的影響。",
    "ActObject": "1. 認識台灣猛禽的種類\r\n2. 探討猛禽生存的條件與困境\r\n3. 省察個人日常行為對於猛禽及其棲地的影響",
    "ActTime": "星期一至星期五，於學期間接受申請。",
    "ActHours": "5小時",
    "JoinDesc": "國小4～6年級",
    "JoinFee": "學生：30元(門票10元、課程費20元)教師及家長：園區門票費"
    },
    {
    "TYP": "3",
    "AduName": "池南自然教育中心",
    "NAduName": "蟲蟲共和國",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=CN-SP1105",
    "ActDesc": "以昆蟲為主角作為課程的主軸，藉由生態遊戲的體驗，引領孩子們認識昆蟲種類及生態，學習與昆蟲做朋友。",
    "ActObject": "1. 認識昆蟲的基本特徵與常見種類\r\n2. 體驗昆蟲平日生活與環境的關係\r\n3. 明白生活行為對環境的影響",
    "ActTime": "星期一至星期五，於學期間接受申請。",
    "ActHours": "3小時",
    "JoinDesc": "幼兒園",
    "JoinFee": "學生：30元(門票10元、課程費20元)教師及家長：園區門票費"
    },
    {
    "TYP": "3",
    "AduName": "池南自然教育中心",
    "NAduName": "昆蟲特攻隊",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=CN-SP1107",
    "ActDesc": "昆蟲特攻隊出發了！我們將帶領小朋友認識百變多樣的昆蟲家族，藉由觀察瞭解昆蟲的生活習性，並思考日常生活行為對於昆蟲的衝擊。你準備好了嗎？讓我們一同來探索昆蟲的秘辛吧！",
    "ActObject": "1. 認識昆蟲的基本特徵\r\n2. 瞭解昆蟲的生活習性\r\n3. 思考日常行為對於昆蟲生存的影響",
    "ActTime": "星期一至星期五，於學期間接受申請。",
    "ActHours": "5小時",
    "JoinDesc": "國小1～3年級",
    "JoinFee": "學生：30元(門票10元、課程費20元)教師及家長：園區門票費"
    },
    {
    "TYP": "3",
    "AduName": "池南自然教育中心",
    "NAduName": "森林大冒險",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=CN-SP1108",
    "ActDesc": "森林是陸地上重要的生態系統，同時也是人類文明發展的搖籃。期待新森林文化課程的普及與深化，讓我們依循林業文化演進歷程，認識台灣寶貴的森林遺產，重新搭建人與自然的和諧關係。",
    "ActObject": "1. 瞭解林業文化發展脈絡\r\n2. 認識森林的價值及功能\r\n3. 省察日常行為對於森林生態的衝擊\r\n4. 培養團隊互助精神",
    "ActTime": "星期一至星期五，於學期間接受申請。\r\n",
    "ActHours": "5小時",
    "JoinDesc": "國中",
    "JoinFee": "學生：30元(門票10元、課程費20元)教師及家長：園區門票費。木頭DIY加價購，推廣價30元/人"
    },
    {
    "TYP": "3",
    "AduName": "池南自然教育中心",
    "NAduName": "島嶼奏鳴曲",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=CN-SP1109",
    "ActDesc": "人類文明過度的發展，使得自然環境嚴重惡化，造成氣候變遷、環境污染、物種滅絕、人類傳染病蔓延等問題，身為年輕世代當以怎樣的態度與行為來面對這些危機。透過活動課程，我們將引導學員省思人類行為對於生態環境的威脅，並尋求具體的環境行動，重新連結人與自然間的和諧關係。",
    "ActObject": "1. 察覺地球環境資源的有限性\r\n2. 體認環境變遷對於人類及其他生物的影響\r\n3. 重視人類對於森林及其他生物應負的責任\r\n4. 探討社區參與及公民行動的具體策略",
    "ActTime": "星期一至星期五，於學期間接受申請。",
    "ActHours": "5小時",
    "JoinDesc": "高中",
    "JoinFee": "學生：45元(門票25元、課程費20元)教師及家長：園區門票費"
    },
    {
    "TYP": "3",
    "AduName": "池南自然教育中心",
    "NAduName": "黑熊的故事",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=CN-SP1110",
    "ActDesc": "生動且活潑的黑熊課程來囉！在這堂課程裡，小朋友可以知道黑熊在原住民傳說中的有趣故事，瞭解黑熊的日常生活，並且理解人類行為對熊及其生存環境的影響。藉此建立小朋友愛護動物的觀念，讓孩子成為保護台灣黑熊的小尖兵。",
    "ActObject": "1. 了解黑熊的生態習性及生態地位\r\n2. 認識原住民文化傳統下，黑熊與人類互動的關係\r\n3. 探究黑熊的生存威脅\r\n4. 反思人類行為對於黑熊的衝擊",
    "ActTime": "星期一至星期五，於學期間接受申請。",
    "ActHours": "5小時",
    "JoinDesc": "國小1～3年級",
    "JoinFee": "學生：30元(門票10元、課程費20元)教師及家長：園區門票費"
    },
    {
    "TYP": "3",
    "AduName": "池南自然教育中心",
    "NAduName": "環境永續課程",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=CN-SP1111",
    "ActDesc": "為因應各級學校的不同需求，本中心另規劃環境永續戶外教學課程，相關訊息，請洽池南自然教育中心教育推廣組(03)864-1594＃15，歡迎有意之學校團體報名申請。",
    "ActObject": null,
    "ActTime": "星期一至星期五，於學期間接受申請。",
    "ActHours": "來電洽詢",
    "JoinDesc": "幼兒園、國小、國中、高中、大學及研究所",
    "JoinFee": "來電洽詢"
    },
    {
    "TYP": "3",
    "AduName": "池南自然教育中心",
    "NAduName": "黑熊偵察隊",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=CN-SP1112",
    "ActDesc": "以森林為家的台灣黑熊雖然名聲響亮亦有不少以其形象作為設計的作品，然而其族群數量卻始終難以令人樂觀。我們將透過角色扮演、影片以及遊戲體驗等方式一起認識台灣黑熊的生存困境並思考每個人所能進行的保育行動。",
    "ActObject": "1. 瞭解台灣黑熊與森林保育的危機\r\n2. 覺知社會上各種角色對台灣森林與黑熊的責任\r\n3. 尋求友善環境的生活方式",
    "ActTime": "星期一至星期五，於學期間接受申請。",
    "ActHours": null,
    "JoinDesc": "國小4～6年級",
    "JoinFee": "學生:30元(門票10元、課程費20元) 教師及家長:園區門票費。木頭DIY加價購，推廣價30元/。"
    },
    {
    "TYP": "3",
    "AduName": "池南自然教育中心",
    "NAduName": "【線上課程】轉角遇見蜂+蜂月桃DIY",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動14天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=CN-SP1113",
    "ActDesc": "你是否曾經在戶外遇見蜂呢?\r\n是忙碌的小蜜蜂、毛茸茸的熊蜂還是帥氣又勇敢的虎頭蜂?\r\n蜂類是大自然裡不可或缺的一份子，關於牠，我們還有很多秘密想跟大家分享!\r\n讓我們一起去神秘的蜂世界探險吧!\r\n\r\n【轉角遇見蜂-課程簡介】\r\n一. 認識虎頭蜂的親戚們\r\n二. 虎頭蜂跟蜜蜂的不同\r\n三. 虎頭蜂的家在哪?\r\n四. 虎頭蜂吃什麼？\r\n五. 虎頭蜂攻擊人的原因\r\n六. 蜂對我們的好處\r\n\r\n【蜂月桃DIY-課程簡介】\r\n因疫情影響無法來山上走走嗎?那就讓我們把森林送到大家手上吧!\r\n邀請大家一起體驗手做的樂趣，感受月桃的芬芳，讓圓滾滾的熊蜂療育大家的身心。",
    "ActObject": "1.讓學生認識到虎頭蜂與蜜蜂間的外觀差異。\r\n2.破除學生對於虎頭蜂的誤解。\r\n3.讓學生學習到蜂類對於森林及人類的益處。\r\n4.讓學生學習到蜂類維持森林環境平衡的重要性。",
    "ActTime": "課程時間共90分鐘，含中間10分鐘下課時間。\r\n課程日期請老師來電洽詢。",
    "ActHours": null,
    "JoinDesc": "國小1~3年級學生",
    "JoinFee": "每位學生費用199元(含課程、材料、運費、帳管費) "
    },
    {
    "TYP": "3",
    "AduName": "池南自然教育中心",
    "NAduName": "【線上課程】名偵探-黑熊莎士+守護者嘟瑪DIY",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動14天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=CN-SP1114",
    "ActDesc": "黑熊偵探事務所招募見習生，想要成為跟黑熊莎士一樣厲害的黑熊偵探，就必須解開黑熊莎士給大家的任務...\r\n透過任務讓大家了解森林裡常見的住客，並介紹黑熊的各種習性、黑熊所遇見的危機以及我們可以做甚麼來幫助黑熊。\r\n準備好了嗎，讓我們一起來解開謎題吧!\r\n\r\n【名偵探黑熊莎士-課程簡介】\r\n一.神秘的鄰居\r\n二.被誤解的真相\r\n三.黑熊在哪兒\r\n四.森林危機面面觀\r\n\r\n【守護者嘟瑪DIY-課程簡介】\r\n台灣黑熊在布農族語中為Tutumaz(音:嘟瑪，中譯 托馬斯)，意指孔武有力的大英雄。一座森林有了黑熊便像是有了守護神的看顧，守護其他森林裡的生物也守護山下人類的安危。讓我們一起動手製作一隻屬於自己的守護者嘟瑪吧!",
    "ActObject": "1.了解森林中的常見的哺乳類動物。\r\n2.澄清大家對黑熊的誤解。\r\n3.讓學生了解黑熊的棲地、習性、食性、特徵。\r\n4.讓學生意識黑熊所面臨的危機並透過日常行為、行動幫助台灣黑熊。\r\n",
    "ActTime": "課程時間共90分鐘，含中間10分鐘下課時間。 課程日期請老師來電洽詢。",
    "ActHours": null,
    "JoinDesc": "國小4~6年級學生",
    "JoinFee": "每位學生費用199元(含課程、材料、運費、帳管費)"
    },
    {
    "TYP": "3",
    "AduName": "池南自然教育中心",
    "NAduName": "【線上課程】解密森林",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動7天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=CN-SP1115",
    "ActDesc": "本課程將帶領學員認識森林的價值及重要性，並瞭解台灣山林破壞的現況，以及探究林業從業人員的執掌及辛勞，尋求國人對於森林保育與經營政策的支持和參與。",
    "ActObject": "1.體認森林的價值及重要性。\r\n2.探討森林非法濫墾、盜伐與盜採對整體國土的威脅。\r\n3.認識林業從業人員的工作執掌及辛勞。\r\n4.尋求社會對於森林與國土政策支持之有效行動。\r\n",
    "ActTime": "課程時間共50分鐘，課程日期請老師來電洽詢。",
    "ActHours": null,
    "JoinDesc": null,
    "JoinFee": "每位學生費用20元(含課程費與帳管費)"
    },
    {
    "TYP": "3",
    "AduName": "池南自然教育中心",
    "NAduName": "【線上課程】轉角遇見蜂",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動7天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=CN-SP1116",
    "ActDesc": "你是否曾經在戶外遇見蜂呢?\r\n是忙碌的小蜜蜂、毛茸茸的熊蜂還是帥氣又勇敢的虎頭蜂?\r\n蜂類是大自然裡不可或缺的一份子，關於牠，我們還有很多秘密想跟大家分享!\r\n讓我們一起去神秘的蜂世界探險吧!\r\n\r\n【轉角遇見蜂-課程簡介】\r\n一. 認識虎頭蜂的親戚們\r\n二. 虎頭蜂跟蜜蜂的不同\r\n三. 虎頭蜂的家在哪?\r\n四. 虎頭蜂吃什麼？\r\n五. 虎頭蜂攻擊人的原因\r\n六. 蜂對我們的好處\r\n",
    "ActObject": "1.讓學生認識到虎頭蜂與蜜蜂間的外觀差異。\r\n2.破除學生對於虎頭蜂的誤解。\r\n3.讓學生學習到蜂類對於森林及人類的益處。\r\n4.讓學生學習到蜂類維持森林環境平衡的重要性。",
    "ActTime": "課程時間共40分鐘，課程日期請老師來電洽詢。",
    "ActHours": null,
    "JoinDesc": "國小1~3年級學生",
    "JoinFee": "每位學生費用20元(含課程費與帳管費) "
    },
    {
    "TYP": "3",
    "AduName": "池南自然教育中心",
    "NAduName": "【線上課程】名偵探-黑熊莎士",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動7天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=CN-SP1117",
    "ActDesc": "黑熊偵探事務所招募見習生，想要成為跟黑熊莎士一樣厲害的黑熊偵探，就必須解開黑熊莎士給大家的任務...\r\n透過任務讓大家了解森林裡常見的住客，並介紹黑熊的各種習性、黑熊所遇見的危機以及我們可以做甚麼來幫助黑熊。\r\n準備好了嗎，讓我們一起來解開謎題吧!\r\n\r\n【名偵探黑熊莎士-課程簡介】\r\n一.神秘的鄰居\r\n二.被誤解的真相\r\n三.黑熊在哪兒\r\n四.森林危機面面觀\r\n",
    "ActObject": "1.了解森林中的常見的哺乳類動物。\r\n2.澄清大家對黑熊的誤解。\r\n3.讓學生了解黑熊的棲地、習性、食性、特徵。\r\n4.讓學生意識黑熊所面臨的危機並透過日常行為、行動幫助台灣黑熊。\r\n",
    "ActTime": "課程時間共40分鐘， 課程日期請老師來電洽詢。",
    "ActHours": null,
    "JoinDesc": "國小4~6年級學生",
    "JoinFee": "每位學生費用20元(含課程費與帳管費) "
    },
    {
    "TYP": "3",
    "AduName": "池南自然教育中心",
    "NAduName": "環境教育4小時課程-看守森林",
    "NAduType": "3",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=CN-T1103",
    "ActDesc": "森林是全體國人共有的寶貴資產，它具有維持生物多樣性、蓄水保土、淨化空氣、自然教育等功能，與人們的生存息息相關。然而森林管理議題涉及廣泛，需要國人理解與支持，透過課程我們將帶領學員瞭解台灣山林破壞的現況，探究林業從業人員的執掌及辛勞，並尋求國人對於森林與整體國土規劃政策的參與及行動。\r\n每次課程費用：(1)園區門票費及(2)課程基本費1,000元/小時，每班不超過40人",
    "ActObject": "1.體認森林的價值及重要性\r\n2.探討森林非法濫墾、盜伐與盜採對整體國土的威脅\r\n3.認識林業從業人員的工作執掌及辛勞\r\n4.尋求社會對於森林與國土政策支持之有效行動\r\n",
    "ActTime": "週一～週五，遇戶外教學旺季（4、5、10、11月）以週三為主。",
    "ActHours": "240分鐘",
    "JoinDesc": "80人以內，以學校或機關為單位團體預約",
    "JoinFee": "課程費1,000元/每小時-每班(以40人計)，自行購票入園。"
    },
    {
    "TYP": "3",
    "AduName": "池南自然教育中心",
    "NAduName": "凝望家鄉-海之森",
    "NAduType": "3",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=CN-T1104",
    "ActDesc": "海岸保安林具有阻滯季節強風、風砂、鹽害、潮害之功能，保護內陸村莊居民及農地的安全。長久以來，林務局投入極大心力及經費，為國人守護海岸保安林的完整性。本課程帶領學員了解海岸保安林的組成、功能與經營困境，體會海岸保安林的價值，同時促進社會大眾對海岸保安林的認識與愛護。",
    "ActObject": "1. 認識海岸林環境特色與植物特性。\r\n2. 連結人們與海岸林的情感。\r\n3. 理解海岸林保護人類生命財產的價值與功能。\r\n4. 尋求共同守護海岸林的策略與方法。",
    "ActTime": "週一～週五，遇戶外教學旺季（4、5、10、11月）以週三為主。",
    "ActHours": "240分鐘",
    "JoinDesc": "學校教職人員、機關團體",
    "JoinFee": "課程費1,000元/每小時-每班(以40人計)，自行購票入園。 餐食自理"
    },
    {
    "TYP": "3",
    "AduName": "池南自然教育中心",
    "NAduName": "綠色大地工作坊",
    "NAduType": "3",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=CN-T1105",
    "ActDesc": "花蓮林區管理處為推展自然教育中心，盼與教育單位、林業人員、國家森林志工、民間團體之成員一同成長，特辦理各項「綠色大地工作坊」，共同為提升環境教育領域之教學品質而努力。",
    "ActObject": "1.認識自然教育中心理念。\r\n2.瞭解池南自然教育中心環境與教學設施。\r\n3.環境教育課程分享與體驗。\r\n4.建立夥伴關係及交流機會。",
    "ActTime": "週一至週五 上午09：00～11：30或下午13：30～16：00(其它時間請電洽)",
    "ActHours": null,
    "JoinDesc": "社會大眾，以團體為單位預約申請。",
    "JoinFee": "課程費1,000元/每小時-每班(以40人計)，自行購票入園，或詳見研習簡章。"
    },
    {
    "TYP": "3",
    "AduName": "池南自然教育中心",
    "NAduName": "森林解密行動",
    "NAduType": "3",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=CN-T1106",
    "ActDesc": "從森林基礎調查出發，讓學習者深入瞭解自我碳足跡管理與氣候變遷之關係，進而理解森林經營管理的重要性與所面臨的挑戰。",
    "ActObject": "1. 體驗日常生活中排碳與氣候變遷的關聯性\r\n2. 認識森林環境監測的方法與監測數據的意義\r\n3. 體驗林務人員森林調查工作並瞭解其辛勞\r\n4. 覺知森林經營管理的重要性及對碳儲存的影響\r\n5. 認同自我碳足跡管理的必要\r\n6. 願意支持森林管理單位之森林經營管理政策",
    "ActTime": "週二~週五(週六依情形而定)，遇戶外教學旺季（4、5、10、11月）以週三為主。",
    "ActHours": "240分鐘",
    "JoinDesc": "高中~成人，20~30人",
    "JoinFee": "課程費1,000元/每小時-每班(不超40人)，自行購票入園。"
    },
    {
    "TYP": "3",
    "AduName": "池南自然教育中心",
    "NAduName": "森林水世界",
    "NAduType": "3",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=CN-T1107",
    "ActDesc": "水是生命的開端，為生活所必需，在氣候變遷下，已成為珍貴的資源。本課程藉由科學實驗調查，從數據的蒐集與分析中，了解森林與水之間緊密連結的關係，並進一步探討森林為人類社會在水文風險上所帶來的貢獻與價值，瞭解保護與珍惜森林的重要意義。",
    "ActObject": "1. 瞭解森林涵養水資源之價值\r\n2. 學習透過實驗、調查與長期監測，瞭解森林在水資源保護上的功能\r\n3. 瞭解不同的土地利用型態，對人類生活所面臨的水土保持災害風險有不同的影響",
    "ActTime": "週二~週五(週六依情形而定)，遇戶外教學旺季（4、5、10、11月）以週三為主。",
    "ActHours": null,
    "JoinDesc": "高中~成人",
    "JoinFee": "課程費1,000元/每小時-每班(40人以內)，自行購票入園。"
    },
    {
    "TYP": "3",
    "AduName": "池南自然教育中心",
    "NAduName": "111年專業成長研習-2：水域活動安全認知與救生操作",
    "NAduType": "3",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=CN-T1110",
    "ActDesc": "本研習邀請具有激流救生專長的講師，介紹從事水域活動所需具備的基本觀念、對環境風險的辨識，並加上實地救生技術演練，增進學員從事戶外野地活動的安全認知。\r\n聯絡人：池南自然教育中心　林大成03-864-1594 #15",
    "ActObject": "1.認識基礎的水域活動觀念\r\n2.學習水域環境的風險辨識與管理\r\n3.了解水域救生器材\r\n4.實地練習水域救援操作",
    "ActTime": "2022/6/23(四) 13:30-16:30室內課(池南森林遊樂區)。 2022/6/24(五) 08:30-16:30戶外課(銅門橋水域)。",
    "ActHours": null,
    "JoinDesc": "10名。(含花蓮林管處同仁5名、森林志工等人5名。依報名順序錄取，並視情形調整名額。另備取５名)",
    "JoinFee": "森林志工(請在報名備註欄表明身份)300元、外部人士1000元。現場繳交。詳見簡章。"
    },
    {
    "TYP": "3",
    "AduName": "東眼山自然教育中心",
    "NAduName": "森林徵信社",
    "NAduType": "1",
    "onAskStart": "2022/01/05",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=DYS-SP1101",
    "ActDesc": "東眼⼭的森林裡潛藏著樹⽊的秘密，我們將邀請孩⼦們擔任解密的偵查員，⽤五感測量森林密碼，重新認識森林中的樹⽊。活動中我們會引導孩⼦透過聽診器、放⼤鏡等調查⼯具描繪樹的形態，讓他們⽤全新的⾓度認識樹⽊的好處及⽤途，並培養孩⼦們愛惜⾃然資源的⽣活態度！",
    "ActObject": "1.\t運用五官感受森林的環境\r\n2.\t認識樹木的生長與構造\r\n3.\t瞭解森林與生物間的相互關係\r\n4.\t願意提出方法保護森林\r\n5.\t記錄樹的各式外觀，包含姿態、特徵、外形、高矮、粗細、葉型等\r\n6.\t增進團隊間的合作與分工\r\n",
    "ActTime": null,
    "ActHours": null,
    "JoinDesc": "3年級～4年級",
    "JoinFee": "每人 100 元(費用含園區保險、課程費；贈門票，停車費依規收取)，每班提供 2 位教師免費。"
    },
    {
    "TYP": "3",
    "AduName": "東眼山自然教育中心",
    "NAduName": "國產材森活",
    "NAduType": "1",
    "onAskStart": "2022/01/05",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=DYS-SP1102",
    "ActDesc": "東眼山過去曾是台灣北部重要的林場，園區內還保有當時伐林、搬運木材用的木馬道、集材機等林業遺跡。我們會帶領學生在自然步道上瞭解林木產業，也會有實作的活動，製作專屬自己的木質小物，希望讓學生在這傳統林場瞭解與體驗木材收集的方式，一起認識友善環境的自然資源利用。\r\n",
    "ActObject": "1.\t感受到先民過去在森林裡伐木集材的辛勞\r\n2.\t瞭解樹木與人類生活的關係\r\n3.\t瞭解生活中的木製品取自森林，且要經過很多步驟才能使用\r\n4.\t認識集材的方式，及認識台灣肖楠的特性及使用用途\r\n5.\t珍惜日常生活中的木製品\r\n6.\t體會團隊合作的重要性\r\n",
    "ActTime": null,
    "ActHours": null,
    "JoinDesc": "5年級-6年級",
    "JoinFee": "每人 100 元(費用含園區保險、課程費；贈門票，停車費依規收取)，每班提供 2 位教師免費。"
    },
    {
    "TYP": "3",
    "AduName": "東眼山自然教育中心",
    "NAduName": "森林趴趴走",
    "NAduType": "1",
    "onAskStart": "2022/01/05",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=DYS-SP1103",
    "ActDesc": "給你一張地圖與指北針，你有辦法辨別現在的位置，又或者知道自己走的路線是對的嗎?本課程將學習運用地圖和指北針，配合小型任務協助學生了解定向技能，透過定向闖關培養團隊精神。",
    "ActObject": "1.\t運用東眼山的環境學習在戶外判別方位的基本方法\r\n2.\t學會操作指北針，及使用指北針判別方位的技能\r\n3.\t認識定向越野地圖上的符號\r\n4.\t體會小組合作以及共同解決問題的重要性\r\n",
    "ActTime": null,
    "ActHours": null,
    "JoinDesc": "5年級-6年級",
    "JoinFee": "每人 100 元(費用含園區保險、課程費；贈門票，停車費依規收取)，每班提供 2 位教師免費。"
    },
    {
    "TYP": "3",
    "AduName": "東眼山自然教育中心",
    "NAduName": "1212上東眼：無痕山林運動",
    "NAduType": "1",
    "onAskStart": "2022/01/05",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=DYS-SP1104",
    "ActDesc": "請、謝謝、對不起，今天起開始森林有禮貌運動！想要有禮貌地進入森林，要記得：「LNT（Leave No Trace）無痕山林七大準則」喔！我們會教你如何事前充分規劃與準備、練習判斷何處適合行走與宿營、如何適當處理垃圾，維護環境、如何減低用火對環境的衝擊、還有如何尊重野生動植物。通往1212的路上，學習森林的有禮貌運動，與夥伴們互相扶持、抵達心之所向吧！",
    "ActObject": "1.\t體會東眼山森林的變化\r\n2.\t認識東眼山森林的形成\r\n3.\t認識無痕山林七大概念、學習登山的技巧與態度\r\n4.\t能夠承諾並願意友善對待自然環境\r\n",
    "ActTime": null,
    "ActHours": null,
    "JoinDesc": "6年級 - 7年級",
    "JoinFee": "每人 100 元(費用含園區保險、課程費；贈門票，停車費依規收取)，每班提供 2 位教師免費。"
    },
    {
    "TYP": "3",
    "AduName": "東眼山自然教育中心",
    "NAduName": "樹守者聯盟：護管員實境解謎",
    "NAduType": "1",
    "onAskStart": "2022/01/05",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=DYS-SP1105",
    "ActDesc": "台灣的森林是由一群「森林護管員」（巡山員）默默守護，負責巡護山林、維持著森林的健康及安全。我們規劃了每木調查、打火、裝備體驗等任務關卡等護管員的任務等你來挑戰，希望能透過互助合作的關卡，培養團隊之間的默契與信任。孩子們，讓我們快手持園區寶藏地圖，運用團隊默契、邏輯思考與生態知識，完成所有機智任務，過關斬將、贏得最後勝利吧！",
    "ActObject": "1.\t瞭解森林護管員的工作內容。\r\n2.\t培養共同合作的技能。\r\n",
    "ActTime": null,
    "ActHours": null,
    "JoinDesc": "6年級～7年級",
    "JoinFee": "每人 100 元(費用含園區保險、課程費；贈門票，停車費依規收取)，每班提供 2 位教師免費。"
    },
    {
    "TYP": "3",
    "AduName": "東眼山自然教育中心",
    "NAduName": "蟲林探險記",
    "NAduType": "1",
    "onAskStart": "2022/01/05",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=DYS-SP1106",
    "ActDesc": "歡迎來到蟲林探險記！這次，讓我們一起化身生態調查員，觀察昆蟲世界的千變萬化。在蟲林小學堂裡，孩子將學習到昆蟲基礎分類、認識科學邏輯的調查方法，並在熟悉調查倫理守則後，專業又不失禮貌的拜訪昆蟲們的棲地。",
    "ActObject": "1. 覺知生活型態對環境及昆蟲的影響\r\n2. 瞭解棲地破壞對昆蟲的影響\r\n3. 認識昆蟲的基本特徵，瞭解昆蟲保護色與棲地選擇的關係\r\n4. 培養愛護昆蟲與森林保育的情懷",
    "ActTime": null,
    "ActHours": null,
    "JoinDesc": "3、4年級",
    "JoinFee": "每人 100 元(費用含園區保險、課程費；贈門票，停車費依規收取)，每班提供 2 位教師免費"
    },
    {
    "TYP": "3",
    "AduName": "東眼山自然教育中心",
    "NAduName": "森林水故鄉",
    "NAduType": "1",
    "onAskStart": "2022/01/05",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=DYS-SP1107",
    "ActDesc": "森林能夠幫我們留住雨水，是水土保持的重要功臣。東眼山位在大漢溪上游，涵養著大漢溪所需要的水源，本課程能讓學生認識森林具有涵養水源之功能。",
    "ActObject": "1. 瞭解森林具有水土保持的重要功能\r\n2. 意識到森林水土保持與溪流污染對人類生活影響是區域性的\r\n3. 瞭解森林水土保持與溪流的關係\r\n4. 認識大漢溪流域（ watershed）及流經的重要城市位置\r\n5. 知道保護森林與溪流是全民的責任",
    "ActTime": null,
    "ActHours": null,
    "JoinDesc": "5 年級-6 年級",
    "JoinFee": "每人 100 元(費用含園區保險、課程費；贈門票，停車費依規收取)， 每班提供 2 位教師免費。"
    },
    {
    "TYP": "3",
    "AduName": "東眼山自然教育中心",
    "NAduName": "東眼奇兵：抗暖化大挑戰",
    "NAduType": "1",
    "onAskStart": "2022/01/05",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=DYS-SP1108",
    "ActDesc": "全球暖化之下海冰漸漸消融，直接影響極地生物！在極端氣候下，地球上的所有生物都面臨威脅。但是，現在開始行動還不遲， 讓我們一起運用各種方法拯救面臨氣候變遷的生物吧！課程中將會介紹森林資源調查，瞭解木材的碳儲存，認識替代能源。透過團隊活動，希望孩子能跟夥伴們互助合作，一齊尋找讓地球退燒的秘方！",
    "ActObject": "1.\t認識溫室效應，瞭解全球暖化對人及生物的影響\r\n2.\t瞭解生活型態對於資源運用及環境的影響\r\n3.\t認識溫室氣體與溫室效應的成因\r\n4.\t瞭解樹木行光合作用能夠將空氣中的二氧化碳吸收存放在木材中\r\n5.\t瞭解改變生活型態是會對生活產生一些不方便的過程\r\n6.\t願意實行生活中可行的方式來減緩全球暖化\r\n7.\t能夠承諾並願意為環境盡自己的一份力量\r\n8.\t能夠說出自己能夠對環境付出哪些有利行動\r\n9.\t瞭解團隊工作相互配合、協調的精神，透過互助合作形成共識完成任務\r\n",
    "ActTime": "確切日期請與本中心聯繫（請提前一個月預約）",
    "ActHours": null,
    "JoinDesc": "5、6年級",
    "JoinFee": "每人 2300 元（費用包含園區保險、住宿、餐費、手冊及課程材料費等，不含停車費。）每班2位教師免費"
    },
    {
    "TYP": "3",
    "AduName": "東眼山自然教育中心",
    "NAduName": "FBI-930檔案：森林科學調查",
    "NAduType": "1",
    "onAskStart": "2022/01/05",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=DYS-SP1109",
    "ActDesc": "FBI的森林探員們注意，任務來了！課程結合森林調查（Forest Biological Investigation, FBI）以及930「救山林」，緊扣「森林生態調查」、「人與森林的關係」與「管理森林的保留區」三大主題，從中學習科學研究的精神，實際規劃、執行、分析並發表屬於自己的生物調查研究，除了透過科學研究解決疑問，更會試著站在管理者的角度思考森林保護政策的訂定。",
    "ActObject": "1.\t瞭解設置自然保留區的意義\r\n2.\t認識食物鏈與能量金字塔的概念，瞭解生物與人類間的關係\r\n3.\t培養科學研究與合作解決問題之態度\r\n4.\t承諾並願意為環境盡自己的一份力量\r\n5.\t設計、操作並呈現一個基礎森林生態調查研究\r\n6.\t針對環境保育策略進行決策\r\n7.\t培養團隊合作、討論與協調的精神\r\n8.\t增加小組合作機會及培養團隊問題解決方式\r\n",
    "ActTime": "確切日期請與本中心聯繫",
    "ActHours": null,
    "JoinDesc": "6年級-7年級",
    "JoinFee": "每人 2300 元（費用包含園區保險、住宿、餐費、手冊及課程材料費等，不含停車費。）"
    },
    {
    "TYP": "3",
    "AduName": "東眼山自然教育中心",
    "NAduName": "挖土機年年作響（線上教學）",
    "NAduType": "1",
    "onAskStart": "2022/01/05",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=DYS-SP1110",
    "ActDesc": "「挖土機年年作響」繪本中每張圖季節、時間的不同，讓學生觀察每張圖的小細節，引導學生思考環境變遷的影響與生活環境的偏好，同時考量到人類發展亦要重視其他生物的生存，體會人類與大自然和平共存的重要性。",
    "ActObject": "1.\t引導思考人類的活動如何改變環境，人類與自然應該如何共存。\r\n2.\t瞭解自然與人類間的相互關係。\r\n3.\t提出自己能做到保護自然的方法。\r\n",
    "ActTime": "2月至11月學期間，每週一至五可預約。\r\n可配合學校課堂時間，一堂課40分鐘。",
    "ActHours": null,
    "JoinDesc": "3年級至4年級，每梯次30人為上限。",
    "JoinFee": "每梯次 1000 元"
    },
    {
    "TYP": "3",
    "AduName": "東眼山自然教育中心",
    "NAduName": "國產材森活（線上教學）",
    "NAduType": "1",
    "onAskStart": "2022/01/05",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=DYS-SP1111",
    "ActDesc": "木頭的利用與人們的生活息息相關，透過 Jamboard 進行小組互動，一同討論、探討使用國產材所帶來的影響，並瞭解如何永續利用自然資源。",
    "ActObject": "1.\t引導思考人類的活動如何改變環境，人類與自然應該如何共存。\r\n2.\t瞭解自然與人類間的相互關係。\r\n3.\t提出自己能做到保護自然的方法。\r\n",
    "ActTime": "2月至11月學期間，每週一至五可預約。\r\n可配合學校課堂時間，一堂課40分鐘。",
    "ActHours": null,
    "JoinDesc": "5年級至6年級，每梯次30人為上限。",
    "JoinFee": "每梯次 1000 元"
    },
    {
    "TYP": "3",
    "AduName": "東眼山自然教育中心",
    "NAduName": "森林徵信社（到校活動）",
    "NAduType": "1",
    "onAskStart": "2022/01/05",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=DYS-SP1112",
    "ActDesc": "我們邀請孩子們擔任解密的偵查員，用五感測量樹木中的密碼，重新認識校園植物。活動中我們引導孩子透過聽診器、放大鏡等調查工具描繪樹的型態，讓他們用全新的角度認識樹木的好處及用途，並培養孩子們愛惜自然資源的生活態度!",
    "ActObject": "1.\t用五感觀察校園中的植物。\r\n2.\t引導思考人類的活動如何改變環境，人類與自然應該如何共存。\r\n3.\t瞭解自然與人類間的相互關係。\r\n4.\t提出自己能做到保護自然的方法。\r\n",
    "ActTime": "2月至11月學期間，每週一至五可預約。\r\n可配合學校課堂時間，上課時間約2節課(80分鐘)。",
    "ActHours": null,
    "JoinDesc": "3年級至4年級，每梯次30人為上限。",
    "JoinFee": "每梯次 1800 元"
    },
    {
    "TYP": "3",
    "AduName": "東眼山自然教育中心",
    "NAduName": "國產材森活（到校活動）",
    "NAduType": "1",
    "onAskStart": "2022/01/05",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=DYS-SP1113",
    "ActDesc": "東眼山過去曾是台灣北部重要的林場，園區內保有當時許多的林業遺跡。本次課程我們帶著東眼山修枝下來的木條，製作專屬的木質小物，希望讓學生瞭解與體驗木材收集的方式，一起認識友善環境的自然資源利用。",
    "ActObject": "1.\t瞭解樹木與人類生活的關係\r\n2.\t瞭解生活中的木製品取自森林，且要經過很多步驟才能使用\r\n3.\t認識集材的方式，及認識台灣肖楠的特性及使用用途\r\n4.\t珍惜日常生活中的木製品。\r\n\r\n",
    "ActTime": "2月至11月學期間，每週一至五可預約。\r\n可配合學校課堂時間，上課時間約2節課(80分鐘)。",
    "ActHours": null,
    "JoinDesc": "5年級至6年級，每梯次30人為上限。",
    "JoinFee": "每梯次2300元"
    },
    {
    "TYP": "3",
    "AduName": "東眼山自然教育中心",
    "NAduName": "定向東遊記",
    "NAduType": "3",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=DYS-T1101",
    "ActDesc": "長期依賴手機與GPS的你，還記得怎麼看紙本地圖嗎？定向運動是種仰賴地圖、指北針與路徑規劃技巧，從某地導航到下一個特定地點的運動。本課程我們要來體驗定向運動，在東眼山的森林中，使用指北針與地圖尋找檢查點，同時各個關卡中還有一些謎題等著你解開，在美麗山林裡揮灑汗水與智慧。",
    "ActObject": "1.\t學會正確操作指北針及使用指北針判別方位的技能\r\n2.\t瞭解定向運動及越野地圖上符號所代表的意義\r\n3.\t獲得森林生態與功能的知識\r\n4.\t培養團隊合作、討論與協調的精神\r\n",
    "ActTime": "2至11月皆可預約，每週二至五可預約，至少於活動前1個月報名。",
    "ActHours": null,
    "JoinDesc": "高中（職）以上，對環境教育及專業成長有興趣之政府機關、學校、企業及民間團體。課程建議人數為20~80",
    "JoinFee": "每人 200 元（含園區保險、課程費，贈門票；停車費依規收取）"
    },
    {
    "TYP": "3",
    "AduName": "東眼山自然教育中心",
    "NAduName": "「學森林」彙編教案演示：森林解密行動",
    "NAduType": "3",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=DYS-T1102",
    "ActDesc": "「學森林」為林務局整合各自然教育中心的特色課程，所彙編成的一套森林環境教育教材。森林解秘行動是以探討森林的「碳滙」為主題。「碳」和你我的生活息息相關，這堂解密行動帶領你重新檢視生活日常的碳足跡，並且走入森林運用基礎的調查方法推算樹木的固碳量，進而瞭解透過森林經營如何有效增加森林的固碳能力。",
    "ActObject": "1.\t體認日常生活中排碳與氣候變遷的關聯性\r\n2.\t認識森林環境監測的方法與監測數據的意義\r\n3.\t體驗林務人員森林調查工作並瞭解其辛勞\r\n4.\t覺知森林經營管理的重要性及對碳儲存的影響\r\n5.\t認同自我碳足跡管理的必要\r\n6.\t願意支持森林管理單位知森林經營管理政策\r\n",
    "ActTime": "2月至11月，每週二至五可預約，至少於活動前1個月報名。",
    "ActHours": null,
    "JoinDesc": "高中（職）以上，對環境教育及專業成長有興趣之政府、學校、企業及民間團體。",
    "JoinFee": "每人 200 元（含園區保險、課程費，贈門票；停車費依規收取）"
    },
    {
    "TYP": "3",
    "AduName": "東眼山自然教育中心",
    "NAduName": "《野生新視界》線上版",
    "NAduType": "3",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動20天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=DYS-T1103",
    "ActDesc": "台灣面積雖僅三萬六千平方公里，卻擁有豐富的生物多樣性，據估計，台灣約有三成的物種屬於台灣特有種，比例之高是世界少有。我們將以世界自然保育基金會（WWF）所發展，中華民國自然生態保育協會（SWAN）所譯的《野生新視界－生物多樣性基礎篇》教材為基礎，結合觀念與資訊，協助教師們探索生物多樣性主題中的生態與社會價值。",
    "ActObject": "1.\t增進生物多樣性的知識\r\n2.\t瞭解生物多樣性對人類的重要性\r\n3.\t思考生物多樣性主題式教學的可能性\r\n4.\t瞭解東眼山自然教育中心所提供之環境教育方案及活動資訊\r\n",
    "ActTime": "2月至11月，每週二至五可預約，至少於活動前1個月報名。",
    "ActHours": null,
    "JoinDesc": "新竹林區管理處轄內範圍，包括新北市（淡水河以南）、桃園市、新竹縣市與苗栗縣之高中（職）以下學校教師，",
    "JoinFee": "每場2000元"
    },
    {
    "TYP": "3",
    "AduName": "東眼山自然教育中心",
    "NAduName": "到校研習《巨人的眼睛》 ",
    "NAduType": "3",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=DYS-T1104",
    "ActDesc": "東眼山自然教育中心以「聯結森林與人、營造永續生活、推動環境倫理」為宗旨推動森林環境教育內涵， 歷經 13 年發展出許多教案，並將發展成熟的七套教案 彙編成《巨人的眼睛》環境教育教材 。這七套教案分別關切森林生態、森林經營、生活永續等主題面向，並採用自然觀察、體驗、團隊活動、科學探究、議題探討等教學方法進行，由淺入深地提供教育人員實施環境教育課程的想像。",
    "ActObject": "1. 增進教師對東眼山教案認識\r\n2. 增進教師對森林環境教育認識\r\n3. 對森林生態、森林經營、生活永續有深入的認識\r\n4. 瞭解東眼山自然教育中心所提供之環境教育方案及活動資訊",
    "ActTime": "全年皆可，以週一、週二及週五為優先。",
    "ActHours": null,
    "JoinDesc": "新竹林區管理處轄內範圍，包括新北市（淡水河以南）、桃園市、新竹縣市與苗 栗縣之高中（職）以下學校教師",
    "JoinFee": "2000元/場"
    },
    {
    "TYP": "3",
    "AduName": "東眼山自然教育中心",
    "NAduName": "東眼山自然教育中心經營管理經驗分享",
    "NAduType": "3",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=DYS-T1105",
    "ActDesc": "東眼山自然教育中心在林務局與新竹林管處的支持下經營十多年，因此我們期待能將過去累積多年的教育方案、人員專業發展、設施強化改善、營運管理等面向的經驗，分享給其他環境教育人員和場所，藉由相互交流學習，整體提升社會環境教育工作之品質。",
    "ActObject": "1.\t認識東眼山自然教育中心發展歷程\r\n2.\t瞭解中心課程規劃、經營理念及所面臨挑戰等，藉此開啟各環境學習中心之交流機會\r\n",
    "ActTime": "全年皆可，以週一、週二及週五為優先。",
    "ActHours": null,
    "JoinDesc": "對自然教育中心經營及發展有興趣之政府、學校單位或民間團體及企業。",
    "JoinFee": "2,000元/小時"
    },
    {
    "TYP": "3",
    "AduName": "東眼山自然教育中心",
    "NAduName": "《臘個植人》線上版",
    "NAduType": "3",
    "onAskStart": "2022/04/17",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=DYS-T1107",
    "ActDesc": "臘葉標本是一種為了有效且便捷的長久保存植物方式，自四百多年前世界上第一份蠟葉標本製作完成至今，臘葉標本為無數植物研究提供了直接且有力的證據。本課程將介紹製作蠟葉標本的原因及前置流程（包括修枝、乾燥等），還會指導學員如何製作一份臘葉標本。除了學會如何判讀蠟葉標本及其重要性，更可以把來自東眼山的回憶保存起來。",
    "ActObject": "1.\t認識台灣山林現況\r\n2.\t瞭解甚麼是臘葉標本及如何製作臘葉\r\n3.\t知道如何製作一份臘葉標本",
    "ActTime": "每次2小時/線上課程",
    "ActHours": null,
    "JoinDesc": null,
    "JoinFee": "4000元/每場次"
    },
    {
    "TYP": "3",
    "AduName": "東眼山自然教育中心",
    "NAduName": "暑假營隊｜過夜吧~東眼之森：實境森林任務攻略",
    "NAduType": "2",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=DYS-TA1117",
    "ActDesc": "簡介：暑假要幹嘛？當然要在森林中來場難忘的探險呀！東眼山之森營隊，要帶孩子認識森林，近距離觀察森林中的生物，孩子還可以大展廚藝，親自烹煮美味的晚餐，發揮創意與想像力，佈置自己的營地，運用自己的聰明才智，團隊互助解決森林闖關任務。我們要讓每個孩子，恣意地在夏天揮灑汗水，與其他孩子做朋友，與生物做朋友，與東眼山做朋友！",
    "ActObject": "1. 培養團隊合作、討論與協調的精神。\r\n2. 體驗森林自然環境。\r\n3. 運用五官感受森林的環境。\r\n4. 建立環境概念、探索自我和建立自信。\r\n5. 培養科學研究與合作解決問題之態度。\r\n6. 承諾並願意為環境盡自己的一份力量。",
    "ActTime": "第一梯次： 07/18~07/22（一～五）\r\n第二梯次： 08/01~08/05（一～五）\r\n",
    "ActHours": null,
    "JoinDesc": "4-7年級",
    "JoinFee": "優惠價：9200元"
    },
    {
    "TYP": "3",
    "AduName": "東眼山自然教育中心",
    "NAduName": "暑假營隊｜東忍學堂之森林修煉帖：攀樹之術",
    "NAduType": "2",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=DYS-TA1118",
    "ActDesc": "東眼山森林將化身為修道場，讓小忍者們修習森林生態、團隊合作和溝通技能。除了有限定的選修課程等你來闖關外，還有讓忍者們互相合作的溫馨晚會、樹上過夜以及夜間生態觀察體驗，和我們一起在森林裡冒險，過一個有美好回憶的暑假。",
    "ActObject": "1.\t讓學生走入森林，認識森林生態。\r\n2.\t以體驗教育(Adventure Education)做為核心價值，讓學生學習團隊合作、自我挑戰及溝通技巧。\r\n3.\t學習攀樹技巧。\r\n",
    "ActTime": "07/04~07/08（一～五）\r\n",
    "ActHours": null,
    "JoinDesc": "4-7年級",
    "JoinFee": "早鳥優惠：12600元"
    },
    {
    "TYP": "3",
    "AduName": "知本自然教育中心",
    "NAduName": "森林觀察家（植物）",
    "NAduType": "5",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=JB-SE1101",
    "ActDesc": "學員們對於森林裡的植物有興趣，藉由中心環教師帶領，用視覺一窺森林層層疊疊的面貌，用聽覺傾聽森林中多樣化的聲音，體驗不同觸覺開啟觀察敏感度，並在活動中傳遞生態知識。\r\n\r\n制式課表【葉脈書籤】課程流程：由中心環教師帶領學員到知本森林裡走一圈，可以發現各種不同樣式的葉子。再回到育苗工作室，DIY課程帶領學員製作出屬於自己專屬的葉脈書籤喔！",
    "ActObject": null,
    "ActTime": null,
    "ActHours": null,
    "JoinDesc": "一般大眾、親子團體",
    "JoinFee": "每人 100 元（包含入園門票、課程費，不含DIY材料費）"
    },
    {
    "TYP": "3",
    "AduName": "知本自然教育中心",
    "NAduName": "線上課程-在家森活好FUN心",
    "NAduType": "5",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=JB-SE1105",
    "ActDesc": "課程規劃融入森林、木材、生活三大概念，透過感受木材的手感、氣味、紋路..等等，認識臺灣森林中的樹木，藉由木製生活用品，建立森林與生活的連結。",
    "ActObject": null,
    "ActTime": null,
    "ActHours": null,
    "JoinDesc": "一般民眾",
    "JoinFee": "課程含材料費"
    },
    {
    "TYP": "3",
    "AduName": "知本自然教育中心",
    "NAduName": "線上課程-小達爾文的探險旅程",
    "NAduType": "5",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=JB-SE1106",
    "ActDesc": "自然教育中心以一系列自然探索歷程，搭配(小達爾文的探險旅程)繪本裡的科學實驗，帶領學童由小地方觀察大自然，並且練習提問的技巧與歸納觀察結果的方法。",
    "ActObject": null,
    "ActTime": null,
    "ActHours": null,
    "JoinDesc": "一般民眾",
    "JoinFee": "含繪本、材料費"
    },
    {
    "TYP": "3",
    "AduName": "知本自然教育中心",
    "NAduName": "木材鮮體驗",
    "NAduType": "5",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動7天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=JB-SE1107",
    "ActDesc": "藉由親手操作、接觸木頭的樂趣中，深入了解樹與人的親近關係，再過實際觀察、接觸及體驗活動來親近植物，並實際走訪生產林木的森林。\r\n\r\n制式課表【動物拼拼樂】課程流程：\r\n森林裡的動物們都被分成一片一片的了！！\r\n您能幫忙把它們組回去嗎？？\r\n透過觸覺及視覺，尋找出相符合的特色，找出拼圖正確的位置。",
    "ActObject": null,
    "ActTime": null,
    "ActHours": null,
    "JoinDesc": null,
    "JoinFee": "(含門票)材料費另計"
    },
    {
    "TYP": "3",
    "AduName": "知本自然教育中心",
    "NAduName": "線上課程-森林護衛隊",
    "NAduType": "5",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=JB-SE1108",
    "ActDesc": "透過線上課程了解森林護管員如何保衛森林及他們的工作內容，冀望由此讓學員了解山林的重要與價值。",
    "ActObject": null,
    "ActTime": null,
    "ActHours": null,
    "JoinDesc": "一般民眾、親子團體",
    "JoinFee": null
    },
    {
    "TYP": "3",
    "AduName": "知本自然教育中心",
    "NAduName": "五感體驗",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=JB-SP1101",
    "ActDesc": "配合學校教學需求與學生年齡以單元模組化的設計概念，組成適合學習者的教學模組執行戶外教學課程。\r\n【五感體驗】：透過視、聽、嗅、觸等感官感覺來提升對於自然環境的認識，同時學習運用感官探索環境的方式。\r\n【核心素養】：A1身心素質與自我精進。B3藝術涵養與美感素養。C1道德實踐與公民意識。\r\n\r\n【課程一：森林大觀園】\r\n知本國家森林遊樂區擁有豐富的自然資源，形成本區特有的生態系統，民國100年運用園區自然資源特色發展知本‧森林故事繪本，透過以園區為場景打造的故事童書，讓大朋友小朋友可以以輕鬆有趣的方式認識知本森林。本課程設計以感人的故事讓低年級學習者進入森林中學習的氛圍，實際進行一系列感官體驗活動使學習者在園區進行自然探索與認識，同時以角色扮演方式帶領學習者進入知本森林的世界，用動物的角度來進行生態觀察與自然體驗活動，除了在活動中傳遞基礎的生態知識之外，並啟發學習者的感知能力、運用感覺來體驗自然，引發學習者對生態環境的保育認知，使其未來願意主動地親近自然，進而培養學習者愛護自然之態度。\r\n【課程二：森林停看聽】\r\n知本森林遊樂區擁有豐富的自然資源，顯著的自然資源包含白榕、大葉桃花心木、白雞油、酸藤等植物群落，此外，也有多種的附生植物共同提供多種動物的食物來源與棲所，形成本區特有的生態系統。本模組讓學童運用感官探索森林，用視覺一窺森林層層疊疊的面貌，用聽覺傾聽森林中多樣化的聲音，體驗粗細滑刺等不同觸覺開啟觀察敏感度，並在活動中傳遞生態知識，使孩子樂於親近自然，進而增加培養學童愛護自然之態度。",
    "ActObject": "【課程一：森林大觀園】\r\n1.讓學習者認識園區自然環境與生態概況。\r\n2.傳遞生物多樣性相關知識。\r\n3.啟發學習者感知能力。\r\n4.培養學習者建立尊重自然生物生命及環境保護的態度。\r\n【課程二：森林停看聽】\r\n1.認識本區自然環境概況、了解森林環境的生物多樣性。\r\n2.啟發學員感知能力並運用五官察覺自然環境。\r\n3.培養學員建立尊重自然、生命的態度。",
    "ActTime": null,
    "ActHours": null,
    "JoinDesc": "幼兒園、1-12年級學生（最適幼兒園、1-4年級學生，限以班級或學校為單位提出申請）",
    "JoinFee": "每人 60 元 "
    },
    {
    "TYP": "3",
    "AduName": "知本自然教育中心",
    "NAduName": "植物生態",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=JB-SP1102",
    "ActDesc": "配合學校教學需求與學生年齡以單元模組化的設計概念，組成適合學習者的教學模組執行戶外教學課程。\r\n【植物生態】：包含基本的植物生長史、植物基本器官構造的認識，運用調查或是探索方式，深度認識以台東為名的植物。\r\n【核心素養】：A2系統思考與解決問題。B1符號運用與溝通表達。C1道德實踐與公民意識。\r\n\r\n【課程一：五彩樹】\r\n知本森林有一個傳說故事，那是不為人知的秘密，從前從前…這裡有知本王國、一棵神奇的五彩樹和一片茂密的森林，然而，森林發生了一件大事，讓森林陷入危機、五彩樹拯救了森林裡的樹木…本課程透過故事引導，帶領學員進入植物的世界，實際觀察認識植物的多樣形態，欣賞樹木的各種樣貌與美麗，同時讓學員實際創作呈現各種植物葉子（花、果實）的多元化，最後藉由實際操作種植種子或移植樹木幼苗（依當時季節及植物的物候狀況調整），讓學員了解照顧、愛護植物的方法。\r\n【課程二：植話植說】\r\n現在生活中有許多植栽是外地進口的，孩子們都接觸到外國來的朋友，我們要讓他認識一下植物界的臺灣原住民，希望可以開啟他們與臺灣原生種植物的溝通橋樑。帶領孩子進入森林中，認識一些原生種植物，觀察樹木的構造，尋找植物的根、莖、葉、種子，進而瞭解其各自不同的功能。本課程以介紹特有的原生植物為出發，帶領孩子認識本土植物以及低海拔森林常見的植物現象，透過實際接觸了解書本中的神奇就出現在真實世界裡，認識臺東在地、多樣且豐富的植物奧秘，更將體認植物與生命、生態之間的關聯性。",
    "ActObject": "【課程一：五彩樹】\r\n1.藉由聆聽故事、實際走訪觀察森林，體驗植物帶給人類的美感。\r\n2.觀察知本國家森林遊樂區中各種植物的葉子形態。\r\n3.認識植物的構造包含葉子、花、果實。\r\n4.藉由繪畫及口頭表達展現自身對於樹葉、花、果實的認知程度。\r\n5.引導學童的想像力與觀察力，體認植物美學，進行繪圖創作。\r\n6.了解樹木由種子、小苗、小樹至大樹的成長過程。\r\n7.藉由實際操作，讓學員了解照顧小樹苗及種子的方法及步驟，感受植物的生命力以及生命成長的感動。\r\n【課程二：植話植說】\r\n1.觀察認識植物各種器官及外觀特徵。\r\n2.認識知本森林遊樂區多樣且豐富的植物。\r\n3.比較植物的葉子、花、果實等的異同及多樣性。\r\n4.了解植物在森林中的生存構造與功能，知道特定植物與其他物種間的關係。",
    "ActTime": null,
    "ActHours": null,
    "JoinDesc": "幼兒園、1-12年級學生（最適3-6年級學生，限以班級或學校為單位提出申請）",
    "JoinFee": "每人 60 元"
    },
    {
    "TYP": "3",
    "AduName": "知本自然教育中心",
    "NAduName": "動物生態",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=JB-SP1103",
    "ActDesc": "配合學校教學需求與學生年齡以單元模組化的設計概念，組成適合學習者的教學模組執行戶外教學課程。\r\n【動物調查】：採用科學調查或是運用客觀性描述等手法，加強對於動物的認識並提升自我對於動物的相關知識。\r\n【核心素養】：A2系統思考與解決問題。B1符號運用與溝通表達。C1道德實踐與公民意識。\r\n\r\n【課程一：蝶舞知本】\r\n蝴蝶翩翩飛舞，緩緩飛過眼前，這裡隨處可見數量與種類繁多的蝴蝶！透過實際觀察與解說活動，近距離地接觸美麗的蝴蝶，認識食草、蜜源植物及其生活史，讓孩子進入蝴蝶的生活中，瞭解蝴蝶的生活環境與一生，進而使孩子建立尊重生命的態度。\r\n【課程二：動物偵探社】\r\n動物是知本森林的主角之一，其美麗的身影讓偶遇的訪客充滿驚奇。本課程結合知本場域的動物資源，運用哺乳動物在森林中覓食及居住遺留的痕跡進行教學活動。課程引導學生進入偵探活動的情境，藉由觀察現場佈置的動物痕跡，小偵探必須找出是哪些動物遺留下的痕跡。在認識動物痕跡種類以及學習簡易科學調查方法後，再扮演偵探實際至戶外環境尋找動物痕跡，比對觀察記錄到的動物痕跡，找出遺留下痕跡的動物。最後藉由遊戲讓學員體會人類行為對動物的影響，進而啟發學員關注動物面臨的生存危機，並願意從自身做起維護環境。",
    "ActObject": "【課程一：蝶舞知本】\r\n1.使學生能辨識場域內常見的蝴蝶。\r\n2.帶領學生認識蝴蝶的基本型態、身體構造及進行其各階段變態的觀察。\r\n3.培養學生團隊默契、合作精神。\r\n4.帶領學生認識蜜源與食草植物，並體認維護植物生長棲地的重要性。\r\n5.帶領學生瞭解幼蟲與成蟲的自我保護機制，體會生物求生存的智慧。\r\n6.使學生產生珍惜、尊重生命的態度。\r\n【課程二：動物偵探社】\r\n1.認識動物痕跡的種類與特徵。\r\n2.學習簡易科學調查方法及運用技巧。\r\n3.培養學童團體合作的精神。 \r\n4. 思考人類行為對野生動物生存的影響與體認自然環境對野生動物生存的重要性。",
    "ActTime": null,
    "ActHours": null,
    "JoinDesc": "幼兒園、1-12年級學生（最適3-9年級學生，限以班級或學校為單位提出申請）",
    "JoinFee": "每人 60 元"
    },
    {
    "TYP": "3",
    "AduName": "知本自然教育中心",
    "NAduName": "木材教育",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=JB-SP1104",
    "ActDesc": "配合學校教學需求與學生年齡以單元模組化的設計概念，組成適合學習者的教學模組執行戶外教學課程。\r\n【木頭教育】：充分運用園區的木頭資源，打造以「木頭」為主的教育課程，包含林木的經營、生產與利用智慧。\r\n【核心素養】：A2系統思考與解決問題。B3藝術涵養與美感素養。C3多元文化與國際理解。\r\n\r\n【課程一：木頭一二三】\r\n以生活中的木製品為概念起點，串聯起生活用品的材質選購到認識木材特性運用為各種用途的木製品，歸納人類運用木材的經驗。利用情境模擬的方式實際走訪生產林木的森林，同時搭配生產消費的概念，探討林木生產的經營價值，最後運用森林撫育後的餘木來進行林木生產的手作體驗，將木頭帶入生活中，貫串森林與人密不可分的依存關係。\r\n",
    "ActObject": "【課程一：木頭一二三】\r\n1.認識生活用品中有許多木頭製品。\r\n2.瞭解不同種類樹木的木頭特性與不同用途的木頭製品。\r\n3.藉由生產消費的歷程，瞭解森林經營(撫育管理)的重要性。\r\n4.運用木頭進行創作，完成一個生活中可用的木頭作品。",
    "ActTime": null,
    "ActHours": null,
    "JoinDesc": "幼兒園、1-12年級學生（最適5-9年級學生，限以班級或學校為單位提出申請）",
    "JoinFee": "每人 60 元"
    },
    {
    "TYP": "3",
    "AduName": "知本自然教育中心",
    "NAduName": "登山倫理",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=JB-SP1105",
    "ActDesc": "配合學校教學需求與學生年齡以單元模組化的設計概念，組成適合學習者的教學模組執行戶外教學課程。\r\n【登山倫理】：強調「向山致敬」的戶外活動觀，提供友善登山的相關技能，運用無痕山林的準則概念傳達兼顧安全與友善環境的內涵。\r\n【核心素養】：A1身心素質與自我精進。C1道德實踐與公民意識。C2人際關係與團隊合作。\r\n\r\n【課程：無痕忍術大學堂】近年來，環境意識的提升與對永續、樂活生活型態的追求，戶外或荒野儼然成為現代人強健體能、療癒心靈與滿足精神的聖堂！然而，過量的遊憩人口或不當的行為，都非常容易對脆弱的自然環境造成危害，如人造廢棄物、廢水、過度的踩踏造成步道或植被的毀損，甚至，野生動物也可能因為誤食人們丟棄的垃圾而受到傷害！此外，戶外技能的知識與環境倫理的不足，也將提高自身的風險。人類的活動在大自然中，確實有牽一髮而動全身的效應，唯有保持戒慎與尊重的態度，才能確保我們所喜愛的自然環境能夠永續保存及個人在野外的自身安全。本模組貫串「Leave No Trace無痕山林」準則，結合園區內自然資源，發展提昇戶外技能、環境覺知與敏感度的環境教育課程。",
    "ActObject": "【課程：無痕忍術大學堂】\r\n1.瞭解「Leave No Trace無痕山林」準則。\r\n2.理解降低環境衝擊的戶外活動技能。\r\n3.覺知人類行為對自然環境的影響。\r\n4.培養尊重山林、永續自然的環境倫理。",
    "ActTime": null,
    "ActHours": null,
    "JoinDesc": "1-12年級學生（最適5-9年級學生，限以班級或學校為單位提出申請）",
    "JoinFee": "每人 60 元"
    },
    {
    "TYP": "3",
    "AduName": "知本自然教育中心",
    "NAduName": "探索體驗",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=JB-SP1106",
    "ActDesc": "配合學校教學需求與學生年齡以單元模組化的設計概念，組成適合學習者的教學模組執行戶外教學課程。\r\n【五感體驗】：透過視、聽、嗅、觸等感官感覺來提升對於自然環境的認識，同時學習運用感官探索環境的方式。\r\n【核心素養】：A1身心素質與自我精進。B3藝術涵養與美感素養。C1道德實踐與公民意識。\r\n\r\n【課程：森林尋寶記】\r\n在遊樂區內的定向運動場域，讓孩子學習地圖判讀、正置地圖等技巧，進行結合定向運動與觀察環境的挑戰，促進孩子發揮觀察力及解決問題能力，並深入了解知本森林遊樂區的環境與生態。",
    "ActObject": "【課程：森林尋寶記】\r\n1.學習地圖判讀方法與定向能力。\r\n2.增加戶外運動、問題解決的經驗。\r\n3.激發學生探索的精神與環境觀察能力。\r\n",
    "ActTime": null,
    "ActHours": null,
    "JoinDesc": "1-12年級學生（最適5-9年級學生，限以班級或學校為單位提出申請）",
    "JoinFee": "每人 60 元"
    },
    {
    "TYP": "3",
    "AduName": "知本自然教育中心",
    "NAduName": "環境議題",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=JB-SP1107",
    "ActDesc": "配合學校教學需求與學生年齡以單元模組化的設計概念，組成適合學習者的教學模組執行戶外教學課程。\r\n【環境議題】：引導學生察覺「碳」、「水」或「森林」對日常生活的影響與現今環境變遷的相關性，同時了解與思考未來解決或面對環境議題的最適方案。\r\n【核心素養】：A2系統思考與解決問題。B2科技資訊與媒體素養。C3多元文化與國際理解。\r\n\r\n【課程一：森林解密行動】\r\n當今環境問題環伺，人們反而因為對環境變化的敏感度降低，失去了對環境持續關注的動力，低估了自身行動對整體環境的影響力。而這樣的認知差距，有可能來自於對議題缺乏更深一層的瞭解。減緩氣候變遷衝擊的方法與途徑之一，是透過森林經營管理來強化碳的減排增匯，藉由課程重新喚醒自我碳足跡管哩，同時從森林基礎監測調查出發，讓學習者深入瞭解並認同森林經營管理的重要性，以及森林對碳匯與氣候變遷的影響，進而面對當今地球公民的時代挑戰。\r\n【課程二：森林水世界】\r\n森林是水的故鄉，不僅為人類提供諸多服務，更是其生命財產安全的重要保衛者。而水是生命的開端，為生活所必需，在氣候變遷下，已成為珍貴的資源。本課程由科學實驗調查，從數據的蒐集與分析中，瞭解森林與水之間緊密連結的關係，並進一步探討森林為人類社會在水文風險上所帶來的貢獻與價值，瞭解保護與珍惜森林的重要意義。\r\n【課程三：西歐兔的奇幻旅程】\r\n將二氧化碳擬人化成「西歐兔」，透過故事引導學生認識二氧化碳。在活動中，瞭解二氧化碳與森林、人類的相關性，並思考友善環境的生活方式。",
    "ActObject": "【課程一：森林解密行動】\r\n1.體認日常生活中排碳與氣候變遷的關聯性。\r\n2.認識森林環境監測的方法與監測數據的意義。\r\n3.體驗林務人員森林調查的工作並瞭解其辛勞。\r\n4.覺知森林經營管理的重要性及對碳儲存的影響。\r\n5.認同自我碳足跡管理的必要。\r\n6.願意支持森林管理單位之森林經營管理政策。\r\n【課程二：森林水世界】\r\n1.瞭解森林涵養水資源之價值。\r\n2.學習透過實驗、調查與長期監測，瞭解森林在水資源保護上的功能。\r\n3.瞭解不同的土地利用型態，對人類生活所面臨的水土保持災害風險有不同的影響。\r\n【課程三：西歐兔的奇幻旅程】\r\n1.認識二氧化碳與了解其所帶來的問題。\r\n2.了解森林與二氧化碳之間的關係。\r\n3.以多種方式表達個人對保護森林環境的看法。",
    "ActTime": null,
    "ActHours": null,
    "JoinDesc": "1-12年級學生（最適7-12年級學生，限以班級或學校為單位提出申請）",
    "JoinFee": "每人 120 元"
    },
    {
    "TYP": "3",
    "AduName": "知本自然教育中心",
    "NAduName": "環境教育加油站-開啟木育之門",
    "NAduType": "3",
    "onAskStart": "2022/01/03",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=JB-T1101",
    "ActDesc": "            傳達人、生活、森林之間的關聯，藉由理解木育(樹木教育)概念，進而培養森林永續經營之正確態度與價值；並認識生活中常使用的木材，學習使用手工具，製作有自我風格、手作溫度的木製品。\r\n\r\n",
    "ActObject": null,
    "ActTime": null,
    "ActHours": null,
    "JoinDesc": "各級學校教職員、機關團體。",
    "JoinFee": "包含門票及課程費用，手作DIY材料費依需求另計。"
    },
    {
    "TYP": "3",
    "AduName": "知本自然教育中心",
    "NAduName": "環境教育加油站-環境教育方案發展",
    "NAduType": "3",
    "onAskStart": "2022/01/03",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=JB-T1102",
    "ActDesc": "認識知本自然教育中心的環境教育課程規劃、瞭解課程方案設計所需資源，並體驗課程活動，為本地的環境教育注入更豐沛且多元的能量。",
    "ActObject": null,
    "ActTime": null,
    "ActHours": null,
    "JoinDesc": null,
    "JoinFee": "含門票及課程費用"
    },
    {
    "TYP": "3",
    "AduName": "知本自然教育中心",
    "NAduName": "環境教育加油站-負責任的山林行動",
    "NAduType": "3",
    "onAskStart": "2022/01/03",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=JB-T1103",
    "ActDesc": "思考自我、他人與環境間的關係，並藉著無痕山林(Leave No Trace)的概念提倡尊重自然且負責任的旅遊態度，透過無痕山林行動實踐，提昇學習者戶外技能與環境覺知，培養友善環境之倫理概念。",
    "ActObject": null,
    "ActTime": null,
    "ActHours": null,
    "JoinDesc": null,
    "JoinFee": "含門票及課程費，材料費另計"
    },
    {
    "TYP": "3",
    "AduName": "羅東自然教育中心",
    "NAduName": "池畔賞鳥趣(團體預約)",
    "NAduType": "5",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=LD-SE1101",
    "ActDesc": "看～圓胖胖的鴨子在池畔整理羽毛，聽～愛講話的鷺鷥成群在樹上聊天談心。\r\n天氣冷了，候鳥都來了！\r\n羅東自然教育中心準備好桌遊，讓你透過親子PK大賽，邊玩邊認識鳥類觀察重點；\r\n一人一隻望遠鏡，讓你眼底盡收野鳥的秘密私生活，和孩子一起開心賞鳥趣！",
    "ActObject": "透過觀察認識羅東林場的鳥類資源，學習正確的生物觀察技巧與態度，並透過實際觀察行動，認識生物與自然棲地的關係，進一步思考自身可行的友善環境生活方式，學習與其他生物共生共存的方法。",
    "ActTime": "110年10月~111年2月，除國定假日之外\r\n可預約時段：09：00～11：30 / 14：00～16：30。 每場次2.5小時\r\n※建議預約前先來電詢問可預約日期\r\n※10月9日~10月11日之國定假日不受理預約",
    "ActHours": null,
    "JoinDesc": "國小一年級以上親子組合，10人成團，每梯次上限30人。",
    "JoinFee": "150元/人（含教具教材費、雙筒望遠鏡使用及個人保險費用），午餐自理。"
    },
    {
    "TYP": "3",
    "AduName": "羅東自然教育中心",
    "NAduName": "木要這樣玩(團體預約)",
    "NAduType": "5",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=LD-SE1102",
    "ActDesc": "原木組裝完成，抬抬貓頭鷹的翅膀、轉轉大象的長鼻子，帶著樹皮的動物童玩風味十足。 \r\n來，大人小孩和我們一起到森林中，動手練習修枝技巧，幫助大樹健康成長。 \r\n修下來的枝幹經過設計、組裝後，就成為自然野性又好玩的原木童玩囉！ \r\n週末假日，幫孩子預約一場寓教於樂的手作課，體驗修枝小樂趣、感受木材大魅力！ \r\n這半天，你可以得到： \r\n1.體驗為大樹修枝的技巧 \r\n2.原木童玩材料包一組（價值170元） \r\n3.親子合力組裝、創作原木動物夥伴的天倫樂趣 \r\n4.學習樹木撫育知識",
    "ActObject": "從國產小徑木童玩組裝，了解國產材以及木材多元應用的方式，並藉由修枝實作開啟對森林永續經營的概念，達成愛木、惜木的木育推廣。",
    "ActTime": "110年全年可預約，除八月及連續國定假日之外。\r\n可預約時段：09：00～11：30 / 14：00～16：30。 每場次2.5小時\r\n※建議預約前先來電詢問可預約日期\r\n※4月2日~4月5日、6月12日~6月14日、9月18日~9月21日、10月9日~10月11日之國定假日不受理預約",
    "ActHours": null,
    "JoinDesc": "國小一年級以上親子組合，10人成團，每梯次限30人。",
    "JoinFee": "320元/人(含市價170元/隻原木童玩材料包、教具教材費及個人保險費用) 午餐自理"
    },
    {
    "TYP": "3",
    "AduName": "羅東自然教育中心",
    "NAduName": "夜探林場(團體預約)",
    "NAduType": "5",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=LD-SE1107",
    "ActDesc": "天氣漸暖，在我們準備休息的夜暮時分，許多小生物卻開始伺機而動：\r\n或跨出長腳安靜迅速地躲入夾縫中藏匿、或扯著嗓子唱著各式動人情歌。\r\n黑夜中牠們各懷絕技活動著，張眼細看，還有點點光芒一閃一閃，寂靜的夜裡原來熱鬧無比！\r\n\r\n羅東自然教育中心邀請親子團體、大小朋友來「夜探林場」，\r\n在樹林下、草地中、水池邊訓練眼力，搜索夜間動物，\r\n並學習以正確的方法近距離接觸生物，了解牠們可愛又迷人的生存之道。",
    "ActObject": "學習正確的夜間觀察態度及穿著，藉遊夜間觀察認識羅東林業文化園區的夜間生物，了解其習性以及牠們在大然中所扮演的角色為何。並從生物棲息的不同環境，了解保護棲息環境才是保護生物的最根本方法。",
    "ActTime": "111年4月～9月，每週二~週五可申請，八月及連續國定假日不受理預約。\r\n可預約時段：18：30～20：30 。 每場次2小時\r\n※建議預約前先來電詢問可預約日期\r\n",
    "ActHours": null,
    "JoinDesc": "國小一年級以上親子組合及16歲以上一般大眾，以團體為單位報名",
    "JoinFee": "每人 150 元，10人以下之團體則以場次計費，每場次收費1500元"
    },
    {
    "TYP": "3",
    "AduName": "羅東自然教育中心",
    "NAduName": "【森林共學堂】從林開始主題講座(到校研習場)",
    "NAduType": "5",
    "onAskStart": "2022/03/22",
    "onAskEnd": "活動0天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=LD-SE1108",
    "ActDesc": "森林之於人們，親近又疏遠，我們或許知道森林是地球陸域最大的生態系，但我們因森林而惠益的需求，往往超過自己的想像。\r\n小至個人日常的紙張使用、家具選擇，大至國家推動「2050 淨零排放（Net Zero）」重大政策，都脫離不了大眾對森林資源的使用方式與林業的永續經營型態。森林資源與永續林業，與每個人的日常息息相關，關注森林課題，也與108課綱中強調將知識、能力、態度融合的素養導向教學不謀而合。\r\n為了讓更多教育工作者認識森林生態系服務的價值，了解林業政策在生活中落實的可能，將林業入校園主題融入素養導向的教學活動中，111年度羅東自然教育中心鄭重推出到校講述的「森林共學堂」成人研習，讓我們一起乘著多樣化軌跡走入林業、認識森林、理解永續經營的方案。",
    "ActObject": "1. 簡介森林生態系服務與林業概念等森林素養\r\n2. 介紹森林與林業教學資源\r\n3. 體驗與討論林業課程\r\n",
    "ActTime": "5/4-6/29，每周(三)下午，限8場；\r\n9/5-11/30，每周(三)下午，限12場。",
    "ActHours": null,
    "JoinDesc": "北北基宜地區各級學校、成人學習社團或相關從業人員團體",
    "JoinFee": "6,000元/場，北北基需額外支付往返交通費用，其他預約請逕洽辦理單位。"
    },
    {
    "TYP": "3",
    "AduName": "羅東自然教育中心",
    "NAduName": "【森林共學堂】從林開始主題講座(團體到林場)",
    "NAduType": "5",
    "onAskStart": "2022/03/22",
    "onAskEnd": "活動0天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=LD-SE1109",
    "ActDesc": "森林之於人們，親近又疏遠，我們或許知道森林是地球陸域最大的生態系，但我們因森林而惠益的需求，往往超過自己的想像。\r\n小至個人日常的紙張使用、家具選擇，大至國家推動「2050 淨零排放（Net Zero）」重大政策，都脫離不了大眾對森林資源的使用方式與林業的永續經營型態。森林資源與永續林業，與每個人的日常息息相關，關注森林課題，也與108課綱中強調將知識、能力、態度融合的素養導向教學不謀而合。\r\n為了讓更多教育工作者認識森林生態系服務的價值，了解林業政策在生活中落實的可能，將林業入校園主題融入素養導向的教學活動中，111年度羅東自然教育中心鄭重推出來到羅東林業文化園區的「森林共學堂」成人研習，讓我們一起乘著多樣化軌跡走入林業、認識森林、理解永續經營的方案。",
    "ActObject": "1. 簡介森林生態系服務與林業概念等森林素養\r\n2. 介紹森林與林業教學資源\r\n3. 體驗與討論林業課程",
    "ActTime": "6月份2場次；9-11月4場次。",
    "ActHours": null,
    "JoinDesc": "北北基宜地區各級學校、成人學習社團或相關從業人員。",
    "JoinFee": "宜蘭地區6,000元/場，北北基需額外支付往返交通費用，其他預約請逕洽辦理單位。"
    },
    {
    "TYP": "3",
    "AduName": "羅東自然教育中心",
    "NAduName": "山上人之謎",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=LD-SP1101",
    "ActDesc": "　　載滿木材的火車駛進了竹林車站，羅東林場的五分仔火車、卸木平台與貯木池正等待著大家，歡迎您一起來這裡感受太平山伐木史的轉變，聽聽過去林木生產與羅東鎮發展間的精彩故事。\r\n　　本課程將以劇場方式，回顧太平山林業發展的歷史。並且實際操作木滑道、木馬道等運材工具，認識因地置宜的運材智慧，感受林業人員的辛勞。並藉由扮演工程師，練習設計運材系統，培養學生衡量環境條件進行適當的資源運用的能力。\r\n\r\n※分低年中級(1-4年級)、高年級(5-6年級)，可參考下方「課程說明」。",
    "ActObject": "　　能藉由觀察、比較、實際操作了解各種不同之運材工具；透過統整歸納設計依地型而發展之運材方式；經實際操作體驗能體認太平山林業發展隨時代演進的歷程；能透過運用工具與數學原理估算、計算木材材積解決問題，並初步建立森林資源永續利用的觀念。",
    "ActTime": "【課程時間】\r\n低中年級：1.5~2小時\r\n高年級：2.5小時",
    "ActHours": null,
    "JoinDesc": "1-6年級(視年級排定課程內容與時間)",
    "JoinFee": "半日型課程：公私立國中小學500元/場；安親班等私人團體1,000元/場。"
    },
    {
    "TYP": "3",
    "AduName": "羅東自然教育中心",
    "NAduName": "池畔日誌",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=LD-SP1102",
    "ActDesc": "　　貯木池畔，您會遇見悠游覓食的紅冠水雞、假裝釣客靜靜守候的魚狗，如果您佯裝成一根浮木，您會發現田鷸就站在腳邊、小白鷺則緩緩伸長雙腿降落後方。這個貯木池，現今已然形成一處熱鬧的水上樂園，更是候鳥補充能量的中繼站。\r\n　　在這裡，學生將發揮心靜、眼觀、耳聽、手繪的能力，學習操作望遠鏡、利用圖鑑辨識所觀察到的鳥類，享受池畔賞鳥的樂趣。透過實地鳥類特徵及行為觀察，認識鳥類的多樣棲地，進而探討鳥類行為與不同棲地的關係，瞭解棲地對生物的重要性。",
    "ActObject": "　　學習安靜、眼看、耳聽、手繪與使用望遠鏡等方式，體驗賞鳥的樂趣與要訣。觀察鳥類行為與微棲地的利用，透過型態與棲地間的關聯探討，認識常見的鳥類生態，從而體驗棲地對生物的重要性。\r\n\r\n註：課程內容將視學習年段進行調整。",
    "ActTime": "2.5小時",
    "ActHours": null,
    "JoinDesc": "3-9年級",
    "JoinFee": "半日型課程：公私立國中小學500元/場；安親班等私人團體1,000元/場。 "
    },
    {
    "TYP": "3",
    "AduName": "羅東自然教育中心",
    "NAduName": "水生家族",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=LD-SP1103",
    "ActDesc": "　　苦草「軟骨術」、青萍「水上飄」、水車前「彈射功」、香蒲「飛鼠術」、龍蝨「潛水術」，還有仰泳椿的「划槳術」……，這些都是水中動植物的特異功能。水池中熱鬧的水生動植物們各有其特殊的忍術以適應不同的環境，想知道更多嗎？水生家族等您一起來發現！\r\n　　本課程將培養學生搜尋、觀察、比對圖鑑以及生物分類等技能。透過四大類水生植物的採集，認識水生植物的特殊器官與功能；並藉由觀察水生昆蟲的特殊生存技能及需求的棲地環境，發現水域生態系面臨的威脅。",
    "ActObject": "　　透過觀察認識水生生物的生活適應方式，熟悉觀察、傳達、比較、分類等技能，並體認水生生態系的生存危機。",
    "ActTime": "每週二至週五",
    "ActHours": null,
    "JoinDesc": "4-6年級",
    "JoinFee": "半日型課程：公私立國中小學500元/場；安親班等私人團體1,000元/場。 "
    },
    {
    "TYP": "3",
    "AduName": "羅東自然教育中心",
    "NAduName": "龐德(pond)工作室",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=LD-SP1104",
    "ActDesc": "　　007龐德這次來到了羅東林業文化園區，發現這裡受到氣候及文化的影響，濕地中生態豐富，引發龐德想一探究竟的興趣。龐德發現，濕地除了豐富地球的生物多樣性外，也豐富你我的生活，更是維持地球環境平衡的重要幫手呢！",
    "ActObject": "活動中，將與龐德先生一同走入Pond（池塘）中，進行「螺貝類」、「魚類」的調查工作，認識及操作不同的工具、學習多樣的調查方式，並且測量採集的生物、觀察細緻的身體構造、運動方式等，認識生物適應環境的生存法則及目前所面臨的困境，並透過討論瞭解基本的調查原理。\r\n\r\n\r\n   ★ 本課程分為二類調查物種「螺貝類」、「魚類」。",
    "ActTime": "每週二至週五\r\n※ 為減緩對生物棲地造成的干擾，每月僅受理魚類、螺貝類各1個場次預約。",
    "ActHours": "5小時(全天)",
    "JoinDesc": "4-9年級",
    "JoinFee": "全日型課程：公私立國中小學800元/場；安親班等私人團體1,600元/場。  "
    },
    {
    "TYP": "3",
    "AduName": "羅東自然教育中心",
    "NAduName": "小小大森林",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=LD-SP1105",
    "ActDesc": "　　羅東林業文化園區內，有一座小小卻熱鬧非凡的森林。在這看似小小的森林裡卻有著大大的美麗世界，這裡有初春的綠芽、盛夏的蟬鳴、早秋的藍天、寒冬的細雨，以及數不清的詩意及美景。\r\n　　在小小大森林的課程裡，我們將運用體驗自然活動，引導孩子親身體驗與探索，用雙眼微觀、雙手輕撫，用鼻嗅清香、耳聽蟲鳴，用純真的心感受自然的美好。還等什麼？快來小小大森林，用小小的手探索大大的美麗世界。",
    "ActObject": "　　在小小大森林的課程裡，我們將運用體驗自然活動，引導孩子親身體驗與探索，用雙眼微觀、雙手輕撫，用鼻嗅清香、耳聽蟲鳴，用純真的心感受自然的美好。還等什麼？快來小小大森林，用小小的手探索大大的美麗世界。",
    "ActTime": "每週二至週五",
    "ActHours": "2小時",
    "JoinDesc": "1-3年級",
    "JoinFee": "半日型課程：公私立國中小學500元/場；安親班等私人團體1,000元/場。 "
    },
    {
    "TYP": "3",
    "AduName": "羅東自然教育中心",
    "NAduName": "綠色小精靈",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=LD-SP1106",
    "ActDesc": "　　植物雖然是沈默無聲的一群，卻提供我們美好舒適生活所需的眾多服務。活動運用羅東林業文化園區優美的綠蔭環境，引導學生打開五官認識周遭的植物朋友，並透過腦力激盪與親身操作進行林木測量，進而在擁抱一棵大樹，觀察各種依存大樹生活的生物後，啟發學童與樹木建立親密的關係。\r\n　　課程將觀察認識葉子的各種形態特徵、動腦、動手挑戰林木的測量方法，進而將對樹木的了解與想像，轉化為藝術與美感的創作，建立樹木與人們的親密關係。",
    "ActObject": "　　學習運用觀察認識葉子的各種形態特徵；了解綠色植物與環境、季節變化的關係及生態現象（樹齡、健康狀況等）；並能運用工具與數學原理解決測量過程中的問題；增加學童對樹木的喜愛與同理心；將對樹木的了解與想像化為具體美術創作的練習。",
    "ActTime": "每週二至週五",
    "ActHours": "2.5小時",
    "JoinDesc": "4-6年級",
    "JoinFee": "半日型課程：公私立國中小學500元/場；安親班等私人團體1,000元/場。 "
    },
    {
    "TYP": "3",
    "AduName": "羅東自然教育中心",
    "NAduName": "大樹碳險隊",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=LD-SP1107",
    "ActDesc": "　　森林提供給我們生活所需的眾多服務，就像隱身在我們生活週遭的綠色寶藏一樣。活動中學生們化身為專業的森林護管員，透過樣區內每木調查，為樹木建立資料庫，各組間整合調查數據及進行解讀分析，了解樣區內樹木成長的狀況與人類的關係。並進一步了解樹木吸收二氧化碳的功能及思考人們如何做出減少排碳量的友善行為。",
    "ActObject": "1. 認識每木調查的技能，學習調查工具的使用，分組進行校園樹木直徑及樹高之測量，並記錄下數據。\r\n2. 利用實際的測量體驗，訓練團隊合作及解決問題的能力。\r\n3. 透過調查數據換算成木材體積、木材價格，認識樹木的價值與人類的關係。\r\n4. 將木材體積計換算成樹木吸收二氧化碳的含量，進而了解樹木吸收二氧化碳的功能。透過圖表認識人們各項行為排碳量的多寡與測量結果對照，進而思考出如何做出減少排碳量的友善行為。",
    "ActTime": "每週二至週五",
    "ActHours": "2.5小時",
    "JoinDesc": "4-9年級",
    "JoinFee": "半日型課程：公私立國中小學500元/場；安親班等私人團體1,000元/場。 可提供宜蘭地區到校服務。"
    },
    {
    "TYP": "3",
    "AduName": "羅東自然教育中心",
    "NAduName": "水‧危機百科",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=LD-SP1108",
    "ActDesc": "　　人體內包含70%水份，透過水份的補充，維持生物體運作，「水」對於我們何其重要！但水能載舟，亦能覆舟，滋潤萬物的水資源，在無處宣洩時，也可能造成嚴重的災害發生。我們要如何與「水」和睦相處呢？",
    "ActObject": "　　本課程將透過遊戲進行與實驗操作的方式，瞭解水資源的循環，認識「水」的物理特性與水土災害發生的原因，並思考生活中哪些水資源的使用行為，是友善的利用方式，建立學生對於水環境永續利用的敏感度。",
    "ActTime": "每週二至週五",
    "ActHours": "5小時(全天)",
    "JoinDesc": "5-9年級",
    "JoinFee": "全日型課程：公私立國中小學800元/場；安親班等私人團體1,600元/場。  "
    },
    {
    "TYP": "3",
    "AduName": "羅東自然教育中心",
    "NAduName": "壹路太平老故事",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=LD-SP1109",
    "ActDesc": "　　老故事是一塊土地的靈魂。我們邀請您參與壹路太平老故事導覽活動，坐在五分仔的載客火車上，緬懷昔日森林鐵路的榮景，走進林業時光隧道，回溯檜木啟動的太平山林業歷史，瞭解蘊藏其中的技術與智慧。活動將運用園區內的場域資源，述說過去的老故事，以角色扮演的方式引導參加人員深入了解林木運送的過程與林業文化。\r\n\r\n註：本活動僅適用於搭配一項戶外教學方案的學校班級。",
    "ActObject": "　　瞭解木材從伐木、運送、到貯存的旅程中，所蘊藏的技術與智慧。本導覽活動述說園區內的老故事、參觀各展館，更深入認識與了解林業文化。 ",
    "ActTime": "每週二至週五\r\n\r\n",
    "ActHours": "1.5小時",
    "JoinDesc": "1-9年級",
    "JoinFee": "需搭配一項戶外教學方案成為全日型課程：公私立國中小學800元/場；安親班等私人團體1,600元/場。"
    },
    {
    "TYP": "3",
    "AduName": "羅東自然教育中心",
    "NAduName": "這些「鳥」事",
    "NAduType": "3",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=LD-T1101",
    "ActDesc": "說到「鳥類」，你腦中浮現出哪些鳥的名字呢？這些活潑的飛羽精靈與你我有何關係？而羅東林業文化園區偌大的貯木池又為何變成了水鳥們的樂園？邀請你拿起望遠鏡，細細觀察鳥類的特徵與構造，豎耳聆聽陸鳥的方位及話語，認識常見鳥類並窺探鳥類行為與棲地的利用關係，進而瞭解保護及營造健全棲地對生物的價值。",
    "ActObject": "觀察、認識鳥類的外型、行為與棲地間的相互關聯性，及享受賞鳥樂趣。",
    "ActTime": "週二至週五",
    "ActHours": "2或3小時",
    "JoinDesc": "公立機關團體、學校教師及一般企業團體",
    "JoinFee": "一般成人團體：2000元/小時，公私立高中職：1000元/小時"
    },
    {
    "TYP": "3",
    "AduName": "羅東自然教育中心",
    "NAduName": "林業時光機",
    "NAduType": "3",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=LD-T1102",
    "ActDesc": "半世紀前，羅東林業文化園區的所在地曾是太平山林業最重要的木材集散地，竹林車站、鐵道、森林火車、卸木平台、貯木池等，都蘊藏了過去林業與羅東鎮興起繁榮的發展故事。\r\n本研習將穿越時空，除了帶你一窺「羅東林業文化園區」底蘊，也邀請你閱讀闡述臺灣不同階段的林業發展脈絡，共同拼湊出橫跨千年以上林木資源使用的智慧與發展軌跡。\r\n",
    "ActObject": "認識各個階段與不同自然環境中，林業與林業聚落的發展軌跡與智慧。",
    "ActTime": "週二至週五",
    "ActHours": null,
    "JoinDesc": "公立機關團體、學校教師及一般企業團體",
    "JoinFee": "一般成人團體：2000元/小時，公私立高中職：1000元/小時"
    },
    {
    "TYP": "3",
    "AduName": "羅東自然教育中心",
    "NAduName": "溼樂園",
    "NAduType": "3",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=LD-T1103",
    "ActDesc": "溼地以各種不同型態存在你我周圍，羅東林業文化園區擁有全國最大的貯木池遺跡，今日已轉型成兼具景觀、生態、教育功能的埤塘，不同生物倚靠這溼地撫育，豐富了生物多樣性，更是地球環境不可或缺的服務系統。\r\n親身走入水生池，觀察與探尋溼地生物，學習生物資源調查的方法，感受溼地對於各種生物的重要，瞭解它多樣的功能及面臨的困境。\r\n",
    "ActObject": "濕地植物豐富了地球生物多樣性，也豐富了你我的生活，更是地球環境不可或缺的服務系統。邀請大家認識濕地生態系，一同關心台灣的濕地。",
    "ActTime": "週二至週五",
    "ActHours": null,
    "JoinDesc": "公立機關團體、學校教師及一般企業團體",
    "JoinFee": "一般成人團體：2000元/小時，公私立高中職：1000元/小時"
    },
    {
    "TYP": "3",
    "AduName": "羅東自然教育中心",
    "NAduName": "森林水世界",
    "NAduType": "3",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=LD-T1104",
    "ActDesc": "水從天而來，落到了森林裡，被樹木攔截稱為截留；被土壤吸收稱為入滲；沒被阻擋直衝大地則造成沖蝕，這些作用彼此影響，最終匯聚形成河流。\r\n羅東自然教育中心在園區規劃出一片片森林樣區，你將學習設計實驗與計算方法，模擬森林與降雨如何交互影響土地樣貌，截留了多少又保留了多少？用科學數據檢視這場樹木與降雨的交響曲，瞭解保護水資源與森林環境的重要。\r\n\r\n",
    "ActObject": "瞭解森林涵養水資源之價值，學習透過實驗、調查與長期監測，瞭解森林在水資源保護上的功能。",
    "ActTime": "週二至週五",
    "ActHours": "2到4小時",
    "JoinDesc": "公立機關團體、學校教師及一般企業團體",
    "JoinFee": "一般成人團體：2000元/小時，公私立高中職：1000元/小時"
    },
    {
    "TYP": "3",
    "AduName": "羅東自然教育中心",
    "NAduName": "當個水池神",
    "NAduType": "3",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=LD-T1105",
    "ActDesc": "天啊～原來小小池塘放著不管，會漸漸被植物大軍吞沒、消失、變成陸地！池塘裡的水鳥、昆蟲、螺貝類和魚兒需要你，快來穿上青蛙裝、戴上手套，前往水池，共同維護水域棲地環境！\r\n生態池？景觀池？教學水生池？池塘得維護才不會荒廢。邀請你試著從規劃、設計、施作及維護管理等不同的階段一起加入，創造一個多元利用價值的水域環境，實際踏入水池進行水域環境維護，來場充實又成就感滿滿的工作假期。\r\n",
    "ActObject": "認識水生生物與水域棲地環境的關係，並透過水域維護管理體認棲地維護的重要性。",
    "ActTime": "週二至週五",
    "ActHours": "3或5小時",
    "JoinDesc": "公立機關團體、學校教師及一般企業團體",
    "JoinFee": "一般成人團體：2000元/小時，公私立高中職：1000元/小時"
    },
    {
    "TYP": "3",
    "AduName": "羅東自然教育中心",
    "NAduName": "跨欄高手",
    "NAduType": "3",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=LD-T1106",
    "ActDesc": "由「課程方案、場域設施、經營管理、專案人員」構築成環境學習中心，其中環境教育課程方案是怎麼規劃與設計呢？何謂環境教育？什麼又是課程方案？後續要如何產出、評估與精進？\r\n從資源盤點開始，著手掌握不同場域的特色與發展脈絡；其次，瞭解不同角色的發展使命與內涵，思考獨具特色的課程內容。本研習將透過羅東自然教育中心的案例分享，轉移課程發展經驗，實際進行教育方案體驗與規劃，學習發展專屬各場域的特色課程。\r\n",
    "ActObject": "認識優質的環境學習中心課程方案應具備的元素，理解方案規劃與設計需準備的資源與材料，透過實作練習激發討論、創意想像、設計課程。",
    "ActTime": "週二至週五",
    "ActHours": "3或5小時",
    "JoinDesc": "公立機關團體、學校教師及一般企業團體",
    "JoinFee": "一般成人團體：2000元/小時，公私立高中職：1000元/小時"
    },
    {
    "TYP": "3",
    "AduName": "羅東自然教育中心",
    "NAduName": "森林解密行動",
    "NAduType": "3",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=LD-T1107",
    "ActDesc": "喚醒管理自身碳排放的自覺吧！你知道何謂生活中的「碳足跡」嗎？人們每天的生活究竟產生多少二氧化碳，而這些碳又需要被多少樹儲存固定呢？ \r\n走出戶外操作工具測量樹木，看見大樹對於碳的吸存能力，同時討論如何透過合理的森林經營管理，才能有效增加碳的蓄積、又不因此失去了森林所提供的各項服務，落實減碳的政策與行動支持！\r\n",
    "ActObject": "1. 體認日常生活中排碳與氣候變遷的關聯性。\r\n2. 認識森林環境監測的方法與監測數據的意義。\r\n3. 體驗林務人員森林調查工作並瞭解其辛勞。\r\n4. 覺知森林經營管理的重要性及對碳儲存的影響。\r\n5. 認同自我碳足跡管理的必要。\r\n",
    "ActTime": "週二至週五",
    "ActHours": "2到4小時",
    "JoinDesc": "公立機關團體、學校教師及一般企業團體",
    "JoinFee": "一般成人團體：2000元/小時，公私立高中職：1000元/小時"
    },
    {
    "TYP": "3",
    "AduName": "羅東自然教育中心",
    "NAduName": "羅東之心啟動學習之心 ",
    "NAduType": "3",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動20天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=LD-T1108",
    "ActDesc": "羅東自然教育中心已成長十年，我們的課程到底有什麼特別呢？我們以優質的環境教育學習場域為目標，為此，本研習將提供夥伴深入瞭解中心發展沿革、經營經驗與環境教育課程的發展及內涵，增進環境教育領域的專業知能。",
    "ActObject": "藉由講座、研討、與活動等方式，搭配逐步豐富的場域內涵與課程方案，提供相關領域的專業知能成長。",
    "ActTime": null,
    "ActHours": null,
    "JoinDesc": "公立機關團體、學校教師及一般企業團體",
    "JoinFee": "一般成人團體：2000元/小時，公私立高中職：1000元/小時"
    },
    {
    "TYP": "3",
    "AduName": "雙流自然教育中心",
    "NAduName": "雙流溪望之旅",
    "NAduType": "5",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=SL-SE1101",
    "ActDesc": "水是雙流豐富重要的自然資源，也與我們的日常生活息息相關，雙流溪望之旅將帶著大家至澄澈清涼的內文溪，實地觀察溪流，並認識水生生物和水質的關係。",
    "ActObject": "1.\t認識雙流國家森林遊樂區內的溪流名稱和流域。\r\n2.\t認識水文循環的概念。\r\n3.\t認識水質指標生物並知道其代表的水質指標意義。\r\n4.\t瞭解如何在生活中愛護水資源。",
    "ActTime": "※建議預約前先來電詢問可預約日期※",
    "ActHours": null,
    "JoinDesc": "一般大眾、社福機構、民營機關團體、非營利組織、學校社團及特殊團體，成團人數20~40人。",
    "JoinFee": "1.\t活動費用：每人150元~200元〈視企劃需求酌收費用〉。 2.\t園區門票及停車費依入園規定辦理"
    },
    {
    "TYP": "3",
    "AduName": "雙流自然教育中心",
    "NAduName": "雙流綠野仙蹤",
    "NAduType": "5",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=SL-SE1102",
    "ActDesc": "「森」意盎然、「聲」情款款，在沿山吊橋上可一探樹冠層結構及森林的層次之美，穿梭於層層疊疊的白榕支柱根間，沿途蝶舞翩翩，鳥兒吱喳合鳴，享受源源不絕的森林芬多精，讓人心曠神怡！",
    "ActObject": "1.\t培養對大自然的觀察能力。\r\n2.\t了解動物會利用保護色、警戒色在大自然中求生存。\r\n3.\t感受自然之美俯拾皆是。\r\n4.\t培養關懷大地之心。",
    "ActTime": "※建議預約前先來電詢問可預約日期※",
    "ActHours": "2.5~3.5小時",
    "JoinDesc": "一般大眾、社福機構、民營機關團體、非營利組織、學校社團及特殊團體，成團人數20~40人。",
    "JoinFee": "1.\t活動費用：每人150元~200元〈視企劃需求酌收費用〉。 2.\t園區門票及停車費依入園規定辦理"
    },
    {
    "TYP": "3",
    "AduName": "雙流自然教育中心",
    "NAduName": "雙流飛瀑慢活小旅行",
    "NAduType": "5",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=SL-SE1103",
    "ActDesc": "雙流瀑布是園區中令人流連忘返之地，順著內文溪向前，沿途生態豐富，大冠鷲臨空盤旋，魚群成群悠遊。美麗的筆筒樹就在步道旁，有時可見食蟹獴的足跡。經過彩虹橋，來到美麗的瀑布，享受陰離子洗滌身心，注入氧氣和能量，感受自然。",
    "ActObject": "1.\t認識雙流崩塌地生態工法的復育方式。\r\n2.\t認識溪流生態系和常見生物之指標意義。\r\n3.\t瞭解台灣南部溪流地理及氣候特色。\r\n4.\t瞭解森林涵養水源的功能。\r\n5.\t瞭解溪流環境與人類的關係。\r\n6.\t省思人類應如何善待溪流及環境。",
    "ActTime": "※建議預約前先來電詢問可預約日期※",
    "ActHours": null,
    "JoinDesc": "一般大眾、社福機構、民營機關團體、非營利組織、學校社團及特殊團體，成團人數20~40人。",
    "JoinFee": "1.\t活動費用：每人150元~200元〈視企劃需求酌收費用〉。 2.\t園區門票及停車費依入園規定辦理"
    },
    {
    "TYP": "3",
    "AduName": "雙流自然教育中心",
    "NAduName": "雙流FBI",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=SL-SP1101",
    "ActDesc": "「水」是雙流最重要的資源，也是園區中令人流連忘返之所在。透過親身探索的過程，讓學習者與水親近，察覺水與水生生物之間的關係，思考水生生物的水質指標功能，進而珍惜及愛護水資源。觀察水中生物的種類及型態，體會水與動物的關係，最後透過小組討論與繪製海報，呈現學習的綜合成果。",
    "ActObject": "1.認識雙流國家森林遊樂區內的溪流名稱和流域。\r\n2.討論並說出水文循環的概念。\r\n3.認識水質指標生物並知道其代表的水質指標意義。\r\n4.學習科學調查的方法和流程。\r\n5.調查溪流中的動物並完成記錄。\r\n6.統整調查數據，並提出結論。\r\n7.瞭解如何在生活中愛護水資源。",
    "ActTime": "學期間每週二、四、五。\r\n",
    "ActHours": null,
    "JoinDesc": "4-9年級",
    "JoinFee": "每人50元(不含門票和停車費)"
    },
    {
    "TYP": "3",
    "AduName": "雙流自然教育中心",
    "NAduName": "與大自然捉迷藏",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=SL-SP1102",
    "ActDesc": "本模組的第一個活動【尋找毛線蟲】，透過替藍鵲寶寶找食物的遊戲，讓學習者了解動物會利用保護色和警戒色在大自然中求生存，培養野外觀察的能力和團隊合作的精神。第二個活動【大自然的精靈】讓學習者分組走訪園區內沿山步道，各組皆有教育推廣人員帶領探訪探索點，讓學習者體驗森林的美好。第三個活動【大自然拼圖】，各組學習者將早上在步道中所見到的環境和生物，畫出美好的森林。藉由破壞與重建的過程，體會保護大自然的重要。",
    "ActObject": "1.培養學生對大自然的觀察能力。\r\n2.使學生了解動物會利用保護色、警戒色在大自然中求生存。\r\n3.體會團隊合作。\r\n4.感受自然之美俯拾皆是。\r\n5.培養關懷大地之心。",
    "ActTime": "學期間每週二、四、五。",
    "ActHours": null,
    "JoinDesc": "3-6年級",
    "JoinFee": "每人50元(不含門票和停車費)"
    },
    {
    "TYP": "3",
    "AduName": "雙流自然教育中心",
    "NAduName": "彩虹的故鄉",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=SL-SP1103",
    "ActDesc": "彩虹是陽光透過水滴所創造的美麗作品，白色的陽光折射之後，散開成為紅、橙、黃、綠、藍、紫等多種色光，彩虹除了在雨過天晴出現外，也經常在瀑布或岩石激起的水花中顯現，雙流國家森林遊樂區的陽光和溪流，不但獨具特色，而且是可永續利用的環境資源。在雙流，引導學習者體驗彩虹的故鄉，觀察山林中顏色的變化，認識大自然的顏色與動、植物的生存之道，啓發學習者欣賞大自然豐富色彩的美感，以及親近山林的樂趣。",
    "ActObject": "1.認識光的折射現象\r\n2.觀察生物的各種顏色變化\r\n3.瞭解大自然中生物顏色的意義\r\n4.引導學童體驗並認識環境議題。\r\n5.欣賞自然，運用想像力延伸聯想。\r\n",
    "ActTime": "學期間每週二、四、五。",
    "ActHours": null,
    "JoinDesc": "1-3年級",
    "JoinFee": "每人50元(不含門票和停車費)"
    },
    {
    "TYP": "3",
    "AduName": "雙流自然教育中心",
    "NAduName": "山林的脈動",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=SL-SP1104",
    "ActDesc": "雙流擁有良好的集水區治理教學場域，先讓學習者瞭解何謂集水區、崩塌地、土石流後，現地觀察崩塌地治理方式，再以簡易Stream table模擬降雨與土石流之間的關係，最後藉著扮演不同角色獲得價值澄清。",
    "ActObject": "1.瞭解森林具有水土保持與涵養水源的重要功能。\r\n2.認識雙流崩塌地的成因與治理方式。\r\n3.實際動手操作Stream table，並能說出雨量多寡會帶來的危害和影響。\r\n4.反思如何改變自身行為友善環境。\r\n",
    "ActTime": "學期間每週二、四、五。",
    "ActHours": null,
    "JoinDesc": "10-12年級",
    "JoinFee": "每人50元(不含門票和停車費)"
    },
    {
    "TYP": "3",
    "AduName": "雙流自然教育中心",
    "NAduName": "溪遊記",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=SL-SP1105",
    "ActDesc": "人類的文明大多來自定居河畔，自古許多農業、商業、文化及交通皆與溪流息息相關，溪流生態系是雙流最豐富且重要的資源，雙流瀑布更是園區中令人流連忘返之所在。透過親身循著瀑布步道而上的過程，學生與水親近，體會溪流、生物、地理特及人類的關係。最後透過討論省思人類應如何善待溪流環境。",
    "ActObject": "1.認識雙流崩塌地生態工法的復育方式。\r\n2.認識溪流生態系和常見生物之指標意義。\r\n3.瞭解台灣南部溪流地理及氣候特色。\r\n4.瞭解森林涵養水源的功能。\r\n5.瞭解溪流環境與人類的關係。\r\n6.省思人類應如何善待溪流及環境。\r\n",
    "ActTime": "學期間每週二、四、五。",
    "ActHours": null,
    "JoinDesc": "5-9年級",
    "JoinFee": "每人50元(不含門票和停車費)"
    },
    {
    "TYP": "3",
    "AduName": "雙流自然教育中心",
    "NAduName": "生活智慧王",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=SL-SP1106",
    "ActDesc": "透過認識早期長輩們日常生活的用品，瞭解一代傳一代的生態智慧，實際認識這些植物及其特性，看看長輩們是如何應用於日常生活中。並利用簡單又天然的竹片，體驗好玩又刺激的童玩活動。最後，將森林中俯拾即是的自然素材再利用，製成豐富又有趣的自然臉譜。",
    "ActObject": "1.認識早期的天然生活用品及其原料。\r\n2.認識長輩們的生態智慧及民俗植物的功用。\r\n3.實際體驗竹童玩的樂趣。\r\n4.利用自然素材創作出自己的臉譜。\r\n",
    "ActTime": "學期間每週二、四、五。",
    "ActHours": null,
    "JoinDesc": "1-4年級",
    "JoinFee": "每人50元(不含門票和停車費)"
    },
    {
    "TYP": "3",
    "AduName": "雙流自然教育中心",
    "NAduName": "動物關鍵報告",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=SL-SP1107",
    "ActDesc": "藉由角色扮演，讓同學思考動物死亡的原因，除了大自然原有的食物鏈，人為因素有時也包括在內。讓同學感受即使是不起眼的小動物，仍維繫了食物鏈的平衡。除了體認每個生命都很重要，也覺察生物多樣性的可貴。最後，讓同學了解基本的生態工法和生態廊道的概念，提供台灣目前保護動物的例子，讓各組經由閱讀、討論、分享，拚出台灣地圖，並思考以自己的能力，可以如何保護野生動物。",
    "ActObject": "1.環境覺知與敏感度：能運用五官觀察體驗、探究環境中的事物。\r\n2.環境概念知識：\r\n（1）理解每一種生物維繫著生態系的平衡。\r\n（2）了解台灣保護野生動物的案例及其做法。\r\n3.環境價值觀與態度：尊重各種生物的生存價值，及人與生物間的倫理關係。\r\n4.環境行動技能：運用觀察能力及調查工具認識動物生態。\r\n5.環境行動經驗：學習參與愛護動物的友善行動。\r\n",
    "ActTime": "學期間每週二、四、五。\r\n",
    "ActHours": null,
    "JoinDesc": "5-6年級",
    "JoinFee": "每人50元(不含門票和停車費)"
    },
    {
    "TYP": "3",
    "AduName": "雙流自然教育中心",
    "NAduName": "一同去郊遊",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=SL-SP1108",
    "ActDesc": "本教學模組以「一同去郊遊」為情境主題，讓學童在闖關活動中認識無痕山林七大準則，在遊戲中瞭解前往山區活動如何做好準備，什麼是負責任的行為，並在用餐過程中學習珍惜資源，不留廚餘，最後請孩童將當日所學在聯絡簿上與家人分享，希望藉由親子互動，也能將無痕山林理念傳達給大人，另一特色是包含了評量活動以了解學童的學習成效。",
    "ActObject": "1.環境覺知與敏感度：\r\n（1）覺知人為活動會對環境造成影響。\r\n2.環境概念知識：\r\n（1）瞭解前往山區活動前如何做好準備。\r\n（2）認識無痕山林七大準則，並知道其內容意義。\r\n3.環境價值觀與態度：\r\n（1）瞭解人與環境互相依存，維護山林環境由個人行為做起。\r\n（2）尊重山裡其他的人與動、植物。\r\n4.環境行動技能：\r\n（1）學習如何與野生動物保持安全距離。\r\n（2）能以語言、文字、圖畫表達對無痕山林課程的想法。\r\n",
    "ActTime": "學期間每週二、四、五。\r\n",
    "ActHours": null,
    "JoinDesc": "1-4年級",
    "JoinFee": "每人50元(不含門票和停車費，餐食需自理)"
    },
    {
    "TYP": "3",
    "AduName": "雙流自然教育中心",
    "NAduName": "風動舞林",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=SL-SP1109",
    "ActDesc": "藉由遊戲體會落山風對於樹木型態的影響，並認識台灣各種森林型態及特色，並帶領學員實際到雙流森林之中體驗熱帶季風林的植物特色，了解為什麼這些植物為什麼可以生活在這樣的氣候條件之下，最後讓學員自己決定如何管理森林。",
    "ActObject": "1.環境覺知與敏感度：\r\n(1)觀察及體驗森林生態之美。\r\n(2)知道森林的功能以及森林與人類的關係。\r\n2.環境概念知識：\r\n(1)學習落山風形成的原因。\r\n(2)了解落山風對樹木的影響。\r\n(3)了解台灣森林類型及特色。\r\n(4)認識熱帶季風林的植物特色。\r\n3.環境價值觀與態度：\r\n(1)能觀察及體驗自然生態環境，理解生物互相之間的關係。\r\n4.環境行動技能：\r\n(1)知道森林面對的危機並提出解決方式。\r\n",
    "ActTime": "學期間每週二、四、五。\r\n",
    "ActHours": null,
    "JoinDesc": "5-6年級",
    "JoinFee": "每人50元(不含門票和停車費)"
    },
    {
    "TYP": "3",
    "AduName": "雙流自然教育中心",
    "NAduName": "森林解密行動",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=SL-SP1110",
    "ActDesc": "當今環境問題環伺，人們反而因為對環境變化的敏感度降低，失去了對環境持續關注的動力，低估了自身行動對整體環境的影響力。而這樣的認知差距，有可能來自於對議題缺乏更深一層的瞭解。減緩氣候變遷衝擊的方法與途徑之一，是透過森林經營管理來強化碳的減排增匯。藉由課程重新喚醒自我碳足跡管理，同時從森林基礎監測調查出發，讓學習者深入瞭解並認同森林經營管理的重要性，以及森林對碳匯與氣候變遷的影響，進而面對當今地球公民的時代挑戰。",
    "ActObject": "1. 體認日常生活中排碳與氣候變遷的關聯性。\r\n2. 認識森林環境監測的方法與監測數據的意義。\r\n3. 覺知森林經營管理的重要性及對碳儲存的影響。\r\n4. 認同自我碳足跡管理的必要。\r\n5. 願意支持森林管理單位之森林經營管理政策。\r\n",
    "ActTime": "學期間每週二、四、五。\r\n",
    "ActHours": null,
    "JoinDesc": "10-12年級、大專院校及研究所",
    "JoinFee": "每人50元(不含門票和停車費)"
    },
    {
    "TYP": "3",
    "AduName": "雙流自然教育中心",
    "NAduName": "森林水世界",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=SL-SP1111",
    "ActDesc": "森林是水的故鄉，不僅為人類提供諸多服務，更是其生命財產安全的重要保衛者。而水是生命的開端，為生活所必需，在氣候變遷下，已成為珍貴的資源。本課程藉由科學實驗調查，從數據的蒐集與分析中，了解森林與水之間緊密連結的關係，並進一步探討森林為人類社會在水文風險上所帶來的貢獻與價值，瞭解保護與珍惜森林的重要意義。",
    "ActObject": "1. 瞭解森林涵養水資源之價值。\r\n2. 學習透過實驗、調查與長期監測,瞭解森林在水資源保護上的功能。\r\n3. 瞭解不同的土地利用型態,對人類生活所面臨的水土保持災害風險有不同的影響。\r\n",
    "ActTime": "學期間每週二、四、五。\r\n\r\n",
    "ActHours": null,
    "JoinDesc": "10-12年級、大專院校及研究所",
    "JoinFee": "每人50元(不含門票和停車費)"
    },
    {
    "TYP": "3",
    "AduName": "雙流自然教育中心",
    "NAduName": "五木調查隊",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=SL-SP1112",
    "ActDesc": "臺灣 60% 的國土面積都是森林，與人們的生活息息相關。當全世界都在關注永續森林 的同時，我們對森林又瞭解多少？如何用簡單的方法讓學習者瞭解和關心森林環境的重要？課程中，將從基礎的植物分類及樹木測量開始，學習辨識及調查技巧，瞭解森林的狀況，並利用世界森林時鐘，看見與感受森林被破壞的速度，引發學習者珍惜森林資源的態度，並了解如何在日常生活中支持森林的永續利用。",
    "ActObject": "1. 能辨識植物的各種型態。\r\n2. 學會分類學二分法及檢索表使用方式。\r\n3. 學會樹木測量的方法與技巧。\r\n4. 認識 FSC(Forest Stewardship Council)認證標章及支持友善森林產品。\r\n5. 培養珍惜及愛護森林資源的態度。\r\n",
    "ActTime": "學期間每週二、四、五。\r\n",
    "ActHours": null,
    "JoinDesc": "4-6年級",
    "JoinFee": "每人50元(不含門票和停車費)"
    },
    {
    "TYP": "3",
    "AduName": "雙流自然教育中心",
    "NAduName": "墾丁追追追",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=SL-SP1113",
    "ActDesc": "<font size=\"2\"><font face=\"Arial\">定向運動起源於歐洲，為國際運動及世界運動會正式項目。運用墾丁定向運動設施學習方向判位及地圖判讀，並結合當地資源，透過探索活動來建立團隊合作模式。</font></font>",
    "ActObject": "<div><font size=\"2\">1.學習利用指北針及地圖判別</font><font size=\"2\">方向，</font><font size=\"2\">強</font><font size=\"2\">化</font><font size=\"2\">學生對方位及判圖</font><font size=\"2\">的多</font><font size=\"2\">元</font><font size=\"2\">智能。</font><font size=\"2\"><br></font></div>\r\n<div><font size=\"2\">2.藉由在有限的時間內完成任務</font><font size=\"2\">來學習</font><font size=\"2\">時間控制之觀念。</font></div>\r\n<div><font size=\"2\">3.透過討論和自我挑戰，建立團</font><font size=\"2\">隊溝通</font><font size=\"2\">與合作的觀念。</font></div>\r\n<div><font size=\"2\">4.透過闖關過程，讓學生認</font><font size=\"2\">識特色</font><font size=\"2\">物種及培養探究能力。<a href=\"http://slnc.pixnet.net/album/photo/327064142-%e5%a2%be%e4%b8%81%e8%bf%bd%e8%bf%bd%e8%bf%bd3.jpg\"><img src=\"https://pic.pimg.tw/slnc/1512964167-2039599488_m.jpg\"></a></font></div>",
    "ActTime": "學期間每週二、四、五",
    "ActHours": "9:30 ~ 14:00",
    "JoinDesc": "5-12年級",
    "JoinFee": "若為高中團體依原價收費"
    },
    {
    "TYP": "3",
    "AduName": "雙流自然教育中心",
    "NAduName": "墾丁鳥樂園",
    "NAduType": "1",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=SL-SP1114",
    "ActDesc": "本教案模組對象為國小四到六年級，以「鳥類觀察」為主軸，讓國小四到六年級的學童在參與活動過程中學習如何觀察鳥類，並透過闖關活動了解正確的鳥類觀察態度及方式，最後再以遊戲的方式，讓學童知道目前台灣環境劣化與鳥類之間的關係。",
    "ActObject": "1.\t認識墾丁常見的鳥類。<div>2.\t能使用圖鑑分辨鳥的種類。</div><div>3.\t學習如何使用望遠鏡觀察生物。</div><div>4.\t認識鳥類不同的形態特徵。&nbsp;</div><div>5.\t了解獵捕與環境劣化對鳥類的影響。\r\n</div>\r\n<a href=\"http://slnc.pixnet.net/album/photo/327064217-%e5%a2%be%e4%b8%81%e9%b3%a5%e6%a8%82%e5%9c%922.jpg\"><img src=\"https://pic.pimg.tw/slnc/1512964659-3004127074_m.jpg\"></a>",
    "ActTime": "學期間每週二、四、五",
    "ActHours": "9：30~14：30",
    "JoinDesc": "4~6年級",
    "JoinFee": null
    },
    {
    "TYP": "3",
    "AduName": "雙流自然教育中心",
    "NAduName": "森林解密行動",
    "NAduType": "3",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動0天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=SL-T1101",
    "ActDesc": "減緩氣候變遷衝擊的方法與途徑之一，是透過森林經營管理以強化碳的減排增匯。藉由課程重新自省碳足跡管理，並從森林基礎監測調查出發，讓學習者深入瞭解森林經營管理的重要性，以及森林對碳匯與氣候變遷的影響，進而面對當今地球公民的時代挑戰。",
    "ActObject": "1. 體認日常生活中排碳與氣候變遷的關聯性。\r\n2. 認識森林環境監測的方法與監測數據的意義。\r\n3. 覺知森林經營管理的重要性及對碳儲存的影響。\r\n4. 認同自我碳足跡管理的必要。\r\n5. 願意支持森林管理單位之森林經營管理政策。\r\n",
    "ActTime": "2~11月份，周一、周三為優先。",
    "ActHours": null,
    "JoinDesc": "高中(職)以上、各級學校教師、各機關團體及對環境教育有興趣者，成團人數20~40人。",
    "JoinFee": "每人150元，園區門票及停車費依入園規定辦理，不包含於課程費用。"
    },
    {
    "TYP": "3",
    "AduName": "雙流自然教育中心",
    "NAduName": "森林水世界",
    "NAduType": "3",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動1天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=SL-T1102",
    "ActDesc": "藉由科學實驗調查，從數據的蒐集與分析中，瞭解森林與水之間緊密連結的關係，並進一步探討森林為人類社會在水文風險上所扮演的角色與貢獻，進而體會保護與珍惜森林的重要意義。",
    "ActObject": "1. 瞭解森林涵養水資源之價值。\r\n2. 學習透過實驗、調查與長期監測,瞭解森林在水資源保護上的功能。\r\n3. 瞭解不同的土地利用型態,對人類生活所面臨的水土保持災害風險有不同的影響。\r\n",
    "ActTime": "2~11月份，周一、周三為優先。",
    "ActHours": "3.5~4 小時（可依參加者需求調整）",
    "JoinDesc": "高中(職)以上、各級學校教師、各機關團體及對環境教育有興趣者，成團人數20~40人。",
    "JoinFee": "每人150元，園區門票及停車費依入園規定辦理，不包含於課程費用。"
    },
    {
    "TYP": "3",
    "AduName": "雙流自然教育中心",
    "NAduName": "森林碳鎖家",
    "NAduType": "3",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=SL-T1103",
    "ActDesc": "跟著碳循環的腳步進入生活中，了解自己生活中的排碳並知道樹木的固碳功能，若要減少碳排放的話，必須由自身做起！最後將自己設計一座城市，終極目標為兼顧經濟發展及環保理念。",
    "ActObject": "1.\t能理解森林所提供的生態服務\r\n2.\t能闡述雙流的自然環境帶給自身在環境美學與環境倫理上的感受\r\n3.\t能描述碳循環過程\r\n4.\t能說明自然界中碳儲存於哪些區域\r\n5.\t能舉例哪些人為行為會影響碳循環\r\n6.\t理解碳足跡意思\r\n7.\t知道森林的固碳作用\r\n8.\t學會如何進行樹木測計\r\n",
    "ActTime": "2~11月份，周一、周三為優先。",
    "ActHours": "4小時（可依參加者需求調整）",
    "JoinDesc": "各級學校教師、各機關團體及對環境教育有興趣者，成團人數20~40人。",
    "JoinFee": "每人150元，園區門票及停車費依入園規定辦理，不包含於課程費用。"
    },
    {
    "TYP": "3",
    "AduName": "雙流自然教育中心",
    "NAduName": "生生不息",
    "NAduType": "3",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=SL-T1104",
    "ActDesc": "生物多樣性為目前環境教育重要課題之一，因此擬以中華民國自然生態保育協會(SWAN)所譯之「野生新視界-生物多樣性基礎篇」為基礎，發展「生物多樣性」課程，內容包含生物多樣性是什麼、生物多樣性為什麼重要、生物多樣性現況及如何保育生物多樣性等，從科學、社會、文化等不同的背景來檢視其錯綜複雜的特性，並透過4個活潑有趣的教學活動單元，啟發學習者一同加入探索、分析、評估與討論現存環境議題的行列。",
    "ActObject": "1.認識何謂生物多樣性。\r\n2.瞭解生物多樣性的重要。\r\n3.培養面對環境議題時應有的公民行動。\r\n4.學習如何永續利用自然資源。\r\n",
    "ActTime": "2~11月份，周一、周三為優先。",
    "ActHours": "3-4小時（可依參加者需求調整）",
    "JoinDesc": "各級學校教師、各機關團體及對環境教育有興趣者，成團人數20~40人。",
    "JoinFee": "每人150元，園區門票及停車費依入園規定辦理，不包含於課程費用。"
    },
    {
    "TYP": "3",
    "AduName": "雙流自然教育中心",
    "NAduName": "小水滴的旅行",
    "NAduType": "3",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=SL-T1105",
    "ActDesc": "地球上的總水量無法增加，但我們可以學著保護、保存、管理現有的水資源，透過活動，我們將化身成小水滴，體驗每顆小水滴的獨一無二旅程，並思考如何永續使用珍貴重要的水資源。",
    "ActObject": "1.\t透過角色扮演，體驗水循環。\r\n2.\t了解現代化對水資源的影響。\r\n3.\t了解合作利用水資源的重要性。\r\n4.\t思考如何愛護水資源。\r\n",
    "ActTime": "2~11月份，周一、周三為優先。",
    "ActHours": "3.5小時（可依參加者需求調整）",
    "JoinDesc": "各級學校教師、各機關團體及對環境教育有興趣者，成團人數20~40人。",
    "JoinFee": "每人150元，園區門票及停車費依入園規定辦理，不包含於課程費用。"
    },
    {
    "TYP": "3",
    "AduName": "雙流自然教育中心",
    "NAduName": "雙流環境教育課程體驗與分享",
    "NAduType": "3",
    "onAskStart": "2021/12/01",
    "onAskEnd": "活動30天前",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=SL-T1106",
    "ActDesc": "雙流自然教育中心所開發的環境教育課程主題包含：森林生態、溪流觀察、野生動物、無痕山林…等，藉由體驗課程，發想現地資源可以如何與課程主題及環境教育內涵結合，並透過與中心環師或國家森林志工的座談交流，分享經驗。",
    "ActObject": null,
    "ActTime": "2~11月份，周一、周三為優先。",
    "ActHours": "3-4小時（可依參加者需求調整）",
    "JoinDesc": "各級學校教師、各機關團體及對環境教育有興趣者，成團人數20~40人。",
    "JoinFee": "每人150元，園區門票及停車費依入園規定辦理，不包含於課程費用。"
    },
    {
    "TYP": "3",
    "AduName": "奧萬大自然教育中心",
    "NAduName": "末日森林高峰會",
    "NAduType": "2",
    "onAskStart": "2022/03/28",
    "onAskEnd": "2022/06/19",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=AWD-TA1110",
    "ActDesc": "森林資源在人類的生活扮演著相當重要的角色，無論是生活必需品、建築或飲食等等，皆須使用到森林資源，但是面對人類生活上的需求增加，大面積工業化開採森林資源，以及原始林的盜伐等開發行為，不僅影響野生動物的棲息環境，也大幅增加二氧化碳的排放，加速全球極端氣候的發生，末日的森林危機即將到來！孩子將扮演四個虛擬國家之角色，透過一系列的森林培訓活動，學習世界森林的概況，並面對連鎖的森林末日危機，學習透過團隊合作與人際溝通等方式，尋求解決問題之道。末日的森林危機能否被順利解決呢？",
    "ActObject": "1.\t瞭解國際森林資源使用概況。\r\n2.\t探討如何永續使用森林資源。\r\n3.\t理解木材自給率過低產生的結果。\r\n4.\t培養團隊合作與問題解決能力。",
    "ActTime": "活動日期：2022.07.26-29(二-五)\r\n活動說明：\r\n「末日森林高峰會」為一種情境體驗式的營隊主題，活動運用真實世界的各種危機，如氣候變遷﹅生態保育﹅戰爭等，設計成故事劇本，孩子將成為故事中的國家領導者，面對與解決一連串的危機，尋找讓世界變得更好的可能性。透過活動的引導，孩子逐步學習如何與同儕相處，一起面對困難及挑戰，試著運用團隊合作的方式，解決發生的各種危機事件。過程中，我們將陪著孩子一起面對各式各樣的課題，讓孩子慢慢的發現自己的獨特之處，累積屬於孩子的重要生命經驗。活動結束後，也會將孩子的改變回饋給您。\r\n",
    "ActHours": null,
    "JoinDesc": "暑假後升國小四年級至升國中二年級為原則",
    "JoinFee": "7,000元/人，包含餐食、住宿、交通接駁"
    },
    {
    "TYP": "3",
    "AduName": "東眼山自然教育中心",
    "NAduName": "暑假營隊｜過夜吧~東眼之森：實境森林任務攻略",
    "NAduType": "2",
    "onAskStart": "2022/04/14",
    "onAskEnd": "2022/06/22",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=DYS-TA1117",
    "ActDesc": "簡介：暑假要幹嘛？當然要在森林中來場難忘的探險呀！東眼山之森營隊，要帶孩子認識森林，近距離觀察森林中的生物，孩子還可以大展廚藝，親自烹煮美味的晚餐，發揮創意與想像力，佈置自己的營地，運用自己的聰明才智，團隊互助解決森林闖關任務。我們要讓每個孩子，恣意地在夏天揮灑汗水，與其他孩子做朋友，與生物做朋友，與東眼山做朋友！",
    "ActObject": "1. 培養團隊合作、討論與協調的精神。\r\n2. 體驗森林自然環境。\r\n3. 運用五官感受森林的環境。\r\n4. 建立環境概念、探索自我和建立自信。\r\n5. 培養科學研究與合作解決問題之態度。\r\n6. 承諾並願意為環境盡自己的一份力量。",
    "ActTime": "第一梯次： 07/18~07/22（一～五）\r\n第二梯次： 08/01~08/05（一～五）\r\n",
    "ActHours": null,
    "JoinDesc": "4-7年級",
    "JoinFee": "優惠價：9200元"
    },
    {
    "TYP": "3",
    "AduName": "東眼山自然教育中心",
    "NAduName": "暑假營隊｜過夜吧~東眼之森：實境森林任務攻略",
    "NAduType": "2",
    "onAskStart": "2022/04/14",
    "onAskEnd": "2022/06/22",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=DYS-TA1117",
    "ActDesc": "簡介：暑假要幹嘛？當然要在森林中來場難忘的探險呀！東眼山之森營隊，要帶孩子認識森林，近距離觀察森林中的生物，孩子還可以大展廚藝，親自烹煮美味的晚餐，發揮創意與想像力，佈置自己的營地，運用自己的聰明才智，團隊互助解決森林闖關任務。我們要讓每個孩子，恣意地在夏天揮灑汗水，與其他孩子做朋友，與生物做朋友，與東眼山做朋友！",
    "ActObject": "1. 培養團隊合作、討論與協調的精神。\r\n2. 體驗森林自然環境。\r\n3. 運用五官感受森林的環境。\r\n4. 建立環境概念、探索自我和建立自信。\r\n5. 培養科學研究與合作解決問題之態度。\r\n6. 承諾並願意為環境盡自己的一份力量。",
    "ActTime": "第一梯次： 07/18~07/22（一～五）\r\n第二梯次： 08/01~08/05（一～五）\r\n",
    "ActHours": null,
    "JoinDesc": "4-7年級",
    "JoinFee": "優惠價：9200元"
    },
    {
    "TYP": "3",
    "AduName": "池南自然教育中心",
    "NAduName": "「溯，森林-獨木舟奇遇記」三天兩夜生態探索營隊 ",
    "NAduType": "2",
    "onAskStart": "2022/05/17",
    "onAskEnd": "2022/07/01",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=CN-TA1104",
    "ActDesc": "熱情耀動的夏日時光，是孩子展現活力的時刻，邀請小朋友與我們在美麗的鯉魚潭划獨木舟，飽覽湖光山色；一同走入河谷，回溯蜿蜒溪流，感受奇幻森林的生命脈動；並在農場裡進行創意野炊料理，享受來自土地與自然的美味風味餐。中心期盼藉由豐富有趣的探索教育體驗活動，讓孩子在自然環境裡學習團隊合作，勾勒出屬於自己與仲夏時光的驚奇探索旅程。",
    "ActObject": null,
    "ActTime": "2022年07月14日（四）至07月16日（六）（三天過夜型營隊）。",
    "ActHours": null,
    "JoinDesc": "9月開學後升國小4、5、6年級及國中1年級之學生，每梯次35人",
    "JoinFee": "4,000元（學員負擔門票、獨木舟課程及裝備費、保險費、活動講師費、餐費、交通費及教材等費用）。"
    },
    {
    "TYP": "3",
    "AduName": "池南自然教育中心",
    "NAduName": "「趣，森活-野溪、獨木舟、田園時光」四天三夜生態探索營隊",
    "NAduType": "2",
    "onAskStart": "2022/05/17",
    "onAskEnd": "2022/07/13",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=CN-TA1105",
    "ActDesc": "熱情耀動的夏日時光，是孩子展現活動的時刻，中心將邀請小朋友與我們走入奇幻森林，回溯蜿蜒溪流，划著獨木舟，飽嚐湖光山色，讚嘆自然裡的生命脈動。\r\n\r\n與孩子一同邁開步伐，笑聲迴盪在迷人的田園風光，品嘗土地所饋予的豐盛餐點，中心期盼連結孩子們與土地的情感，創造美好的童年回憶。\r\n",
    "ActObject": null,
    "ActTime": "2022年07月27日（三）至07月30日（六）（四天過夜型營隊）。\r\n",
    "ActHours": null,
    "JoinDesc": "9月開學後升國小4、5、6年級及國中1年級之學生，每梯次35人",
    "JoinFee": "5,350元（學員負擔門票、獨木舟課程及裝備費、保險費、活動講師費、餐費、交通費及教材等費用）。"
    },
    {
    "TYP": "3",
    "AduName": "知本自然教育中心",
    "NAduName": "野森探索趣",
    "NAduType": "2",
    "onAskStart": "2022/06/01",
    "onAskEnd": "2022/06/20",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=JB-TA1101",
    "ActDesc": "由小達爾文的探險旅程繪本拉開序幕，帶領大家一窺生物調查的秘辛，走入知本森林尋找動物留下的蛛絲馬跡，架設紅外線自動相機，捕捉野生動物的秘密生活，設置掉落式陷阱，近距離觀察繽紛的昆蟲世界，最後在徐徐微風和星空的陪伴下，跟著我們來一場夜間動植物的奇遇記吧!!",
    "ActObject": null,
    "ActTime": null,
    "ActHours": null,
    "JoinDesc": "一位大人最多陪伴2名孩童 (建議參與年齡8歲以上，孩童需年滿11歲方可獨自參加本活動)",
    "JoinFee": "含入園門票、餐點費、課程費、保險費及繪本乙本。每增加 1 人酌收費用 550 元/人(不含繪本)。"
    },
    {
    "TYP": "3",
    "AduName": "八仙山自然教育中心",
    "NAduName": "「找樹的人」半日攀樹體驗",
    "NAduType": "3",
    "onAskStart": "2022/04/02",
    "onAskEnd": "2022/06/13",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=BSS-T1105",
    "ActDesc": "邀請《找樹的人》團隊，帶領你安全上樹，體驗從樹木的角度看世界。講師徐嘉君為國內少數研究樹冠層附生植物的學者，致力於尋找世界上的巨木，也為各個樹冠層的植物生態系留下紀錄。藉由攀樹活動親近樹冠層，認識附生植物是環境變遷的重要指標，體會研究員所驚嘆的一樹一世界。",
    "ActObject": "知道攀樹對科學研究的用途、認識樹冠層，知道附生植物對理解氣候變遷之重要性。\r\n",
    "ActTime": "111年6月25日（六）9:00~13:00。",
    "ActHours": null,
    "JoinDesc": "16歲以上民眾",
    "JoinFee": "含講師團隊、器材、保險、課程"
    },
    {
    "TYP": "3",
    "AduName": "奧萬大自然教育中心",
    "NAduName": "奧萬大森林星空帳篷套裝活動",
    "NAduType": "5",
    "onAskStart": "2022/04/11",
    "onAskEnd": "2022/06/23",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=AWD-SE1104",
    "ActDesc": "踏入森林的懷抱，感受著新鮮空氣與花草的芬芳，奧萬大自然教育中心運用森林的各種元素，從主題DIY﹅星空導覽﹅瀑布探險與獵人飯包等活動，打造出豐富且充實的活動主題。尤其餐點更搭配部落的原民風味無菜單料理，讓舌尖體驗不同文化的味道，來奧萬大露營將成為一趟簡單又舒適的旅程。\r\n",
    "ActObject": null,
    "ActTime": null,
    "ActHours": null,
    "JoinDesc": "包團制，僅限14人以上團體，最多28人",
    "JoinFee": "14人一團只要68,999包含活動、餐食帳篷住宿，每帳安排兩名為原則"
    },
    {
    "TYP": "3",
    "AduName": "奧萬大自然教育中心",
    "NAduName": "奧萬大森林星空帳篷套裝活動",
    "NAduType": "5",
    "onAskStart": "2022/04/11",
    "onAskEnd": "2022/07/14",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=AWD-SE1104",
    "ActDesc": "踏入森林的懷抱，感受著新鮮空氣與花草的芬芳，奧萬大自然教育中心運用森林的各種元素，從主題DIY﹅星空導覽﹅瀑布探險與獵人飯包等活動，打造出豐富且充實的活動主題。尤其餐點更搭配部落的原民風味無菜單料理，讓舌尖體驗不同文化的味道，來奧萬大露營將成為一趟簡單又舒適的旅程。\r\n",
    "ActObject": null,
    "ActTime": null,
    "ActHours": null,
    "JoinDesc": "包團制，僅限14人以上團體，最多28人",
    "JoinFee": "14人一團只要68,999包含活動、餐食帳篷住宿，每帳安排兩名為原則"
    },
    {
    "TYP": "3",
    "AduName": "奧萬大自然教育中心",
    "NAduName": "奧萬大森林星空帳篷套裝活動",
    "NAduType": "5",
    "onAskStart": "2022/04/11",
    "onAskEnd": "2022/07/28",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=AWD-SE1104",
    "ActDesc": "踏入森林的懷抱，感受著新鮮空氣與花草的芬芳，奧萬大自然教育中心運用森林的各種元素，從主題DIY﹅星空導覽﹅瀑布探險與獵人飯包等活動，打造出豐富且充實的活動主題。尤其餐點更搭配部落的原民風味無菜單料理，讓舌尖體驗不同文化的味道，來奧萬大露營將成為一趟簡單又舒適的旅程。\r\n",
    "ActObject": null,
    "ActTime": null,
    "ActHours": null,
    "JoinDesc": "包團制，僅限14人以上團體，最多28人",
    "JoinFee": "14人一團只要68,999包含活動、餐食帳篷住宿，每帳安排兩名為原則"
    },
    {
    "TYP": "3",
    "AduName": "羅東自然教育中心",
    "NAduName": "【森林共學堂】從林開始主題講座(散客到林場)",
    "NAduType": "5",
    "onAskStart": "2022/04/01",
    "onAskEnd": "2022/09/23",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=LD-SE1110",
    "ActDesc": "森林之於人們，親近又疏遠，我們或許知道森林是地球陸域最大的生態系，但我們因森林而惠益的需求，往往超過自己的想像。\r\n小至個人日常的紙張使用、家具選擇，大至國家推動「2050 淨零排放（Net Zero）」重大政策，都脫離不了大眾對森林資源的使用方式與林業的永續經營型態。森林資源與永續林業，與每個人的日常息息相關，關注森林課題，也與108課綱中強調將知識、能力、態度融合的素養導向教學不謀而合。\r\n為了讓更多教育工作者認識森林生態系服務的價值，了解林業政策在生活中落實的可能，將林業入校園主題融入素養導向的教學活動中，111年度羅東自然教育中心鄭重推出「森林共學堂」成人研習，讓我們一起乘著多樣化軌跡走入林業、認識森林、理解永續經營的方案。",
    "ActObject": "1. 簡介森林生態系服務與林業概念等森林素養\r\n2. 介紹森林與林業教學資源\r\n3. 體驗與討論林業課程",
    "ActTime": "5/28(六)、6/17(五)、10/7(五)、10/29(六)，下午1點30到4點30，共3小時。",
    "ActHours": null,
    "JoinDesc": "年滿18歲以上之成人、學校教師或教育推廣從業人員。",
    "JoinFee": "含教材教具費用"
    },
    {
    "TYP": "3",
    "AduName": "羅東自然教育中心",
    "NAduName": "【森林共學堂】從林開始主題講座(散客到林場)",
    "NAduType": "5",
    "onAskStart": "2022/04/01",
    "onAskEnd": "2022/10/08",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=LD-SE1110",
    "ActDesc": "森林之於人們，親近又疏遠，我們或許知道森林是地球陸域最大的生態系，但我們因森林而惠益的需求，往往超過自己的想像。\r\n小至個人日常的紙張使用、家具選擇，大至國家推動「2050 淨零排放（Net Zero）」重大政策，都脫離不了大眾對森林資源的使用方式與林業的永續經營型態。森林資源與永續林業，與每個人的日常息息相關，關注森林課題，也與108課綱中強調將知識、能力、態度融合的素養導向教學不謀而合。\r\n為了讓更多教育工作者認識森林生態系服務的價值，了解林業政策在生活中落實的可能，將林業入校園主題融入素養導向的教學活動中，111年度羅東自然教育中心鄭重推出「森林共學堂」成人研習，讓我們一起乘著多樣化軌跡走入林業、認識森林、理解永續經營的方案。",
    "ActObject": "1. 簡介森林生態系服務與林業概念等森林素養\r\n2. 介紹森林與林業教學資源\r\n3. 體驗與討論林業課程",
    "ActTime": "5/28(六)、6/17(五)、10/7(五)、10/29(六)，下午1點30到4點30，共3小時。",
    "ActHours": null,
    "JoinDesc": "年滿18歲以上之成人、學校教師或教育推廣從業人員。",
    "JoinFee": "含教材教具費用"
    },
    {
    "TYP": "3",
    "AduName": "羅東自然教育中心",
    "NAduName": "【森林共學堂】百年樹人種子師資工作坊",
    "NAduType": "5",
    "onAskStart": "2022/06/01",
    "onAskEnd": "2022/07/15",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=LD-SE1112",
    "ActDesc": "無論您是：\r\n站在教育第一線的各級學校老師；\r\n面對木育新課綱一時摸不著頭緒的家長；\r\n或純粹熱愛大自然的森林狂熱者；\r\n\r\n百年樹人種子師資工作坊，將以兩天的時間，帶您走訪林業基地與時光走廊、從職人口中探究林業政策新方向，同時把五套林業課程內涵與操作方法，完整帶著走。未來您可以在校園中與孩子見樹又見林，用療癒方式感受樹木，或者安排公園裡的森林調查，甚至來場談判桌上的林業發展激辯，一起培養具有森林素養的未來公民吧!",
    "ActObject": "●林業政策及森林概念深入校園\r\n●擴大教學範圍，進行林業主題課程教學經驗轉移與推廣",
    "ActTime": "7/20-21（三、四）、11/19-20（六、日），每場2天不過夜",
    "ActHours": null,
    "JoinDesc": "年滿16歲以上之一般民眾（未滿18歲者，報名需檢附家長同意書）",
    "JoinFee": "含教材教具費用"
    },
    {
    "TYP": "3",
    "AduName": "羅東自然教育中心",
    "NAduName": "【森林共學堂】百年樹人種子師資工作坊",
    "NAduType": "5",
    "onAskStart": "2022/06/01",
    "onAskEnd": "2022/11/10",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=LD-SE1112",
    "ActDesc": "無論您是：\r\n站在教育第一線的各級學校老師；\r\n面對木育新課綱一時摸不著頭緒的家長；\r\n或純粹熱愛大自然的森林狂熱者；\r\n\r\n百年樹人種子師資工作坊，將以兩天的時間，帶您走訪林業基地與時光走廊、從職人口中探究林業政策新方向，同時把五套林業課程內涵與操作方法，完整帶著走。未來您可以在校園中與孩子見樹又見林，用療癒方式感受樹木，或者安排公園裡的森林調查，甚至來場談判桌上的林業發展激辯，一起培養具有森林素養的未來公民吧!",
    "ActObject": "●林業政策及森林概念深入校園\r\n●擴大教學範圍，進行林業主題課程教學經驗轉移與推廣",
    "ActTime": "7/20-21（三、四）、11/19-20（六、日），每場2天不過夜",
    "ActHours": null,
    "JoinDesc": "年滿16歲以上之一般民眾（未滿18歲者，報名需檢附家長同意書）",
    "JoinFee": "含教材教具費用"
    },
    {
    "TYP": "3",
    "AduName": "八仙山自然教育中心",
    "NAduName": "仲夏散冊‧森林畫室",
    "NAduType": "3",
    "onAskStart": "2022/05/04",
    "onAskEnd": "2022/07/03",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=BSS-T1108",
    "ActDesc": "繪圖是人類最早描述知識的途徑之一，相較於文字，圖畫更能直觀地描述與傳達資訊。早期的人們基於各種理由進行繪畫，如：紀錄藥用植物的外觀、紀錄稀有動物的外在特徵、宗教祭祀、賞心悅目、歌功頌德、陶冶性情等，不論細緻程度，都使人更貼近這個世界的真實樣貌，無法搭船遠洋，卻能透過一幅畫看到大海另一端的驚奇奧秘。\r\n繪圖相較攝影，需要耗費更多的時間進行觀察、探究，才能將其特徵或行為精細地描繪，使觀賞者能直觀地接受到描述的事實，透過繪圖也更能引人進入大自然無法言喻的驚喜之處。\r\n八仙山國家森林遊樂區內因過去曾為林場，步道平緩適合沿途觀察，多處平坦開闊草地昔日為宿舍區，現適合就地寫生或素描，因此特規劃八仙山生物繪圖系列課程，以走讀、繪圖的角度進入充滿人文與美學氣質的八仙山森林，以文學、美學、植物學的角度認識森林演替、森林生態，細膩觀察森林中各式各樣的生命力，領人感受森林展現的繽紛姿態。",
    "ActObject": "（一）走讀八仙山森林步道。\r\n（二）藉由繪圖，發現生物細緻的樣貌。\r\n（三）感受八仙山森林環境的豐富。\r\n（四）培養自然美學。\r\n",
    "ActTime": "畫一座森林：111年7月16日，星期六，上午10：10-16：00。夜讀森林：111年7月16日，星期六，下午18：45-21：30。一葉知森：111年7月17，星期日，上午10：10-16：00。",
    "ActHours": null,
    "JoinDesc": "18歲以上成人",
    "JoinFee": "包含入園門票、保險、課程材料費、一份點心與講師費"
    },
    {
    "TYP": "3",
    "AduName": "八仙山自然教育中心",
    "NAduName": "仲夏散冊‧森林畫室",
    "NAduType": "3",
    "onAskStart": "2022/05/04",
    "onAskEnd": "2022/07/03",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=BSS-T1108",
    "ActDesc": "繪圖是人類最早描述知識的途徑之一，相較於文字，圖畫更能直觀地描述與傳達資訊。早期的人們基於各種理由進行繪畫，如：紀錄藥用植物的外觀、紀錄稀有動物的外在特徵、宗教祭祀、賞心悅目、歌功頌德、陶冶性情等，不論細緻程度，都使人更貼近這個世界的真實樣貌，無法搭船遠洋，卻能透過一幅畫看到大海另一端的驚奇奧秘。\r\n繪圖相較攝影，需要耗費更多的時間進行觀察、探究，才能將其特徵或行為精細地描繪，使觀賞者能直觀地接受到描述的事實，透過繪圖也更能引人進入大自然無法言喻的驚喜之處。\r\n八仙山國家森林遊樂區內因過去曾為林場，步道平緩適合沿途觀察，多處平坦開闊草地昔日為宿舍區，現適合就地寫生或素描，因此特規劃八仙山生物繪圖系列課程，以走讀、繪圖的角度進入充滿人文與美學氣質的八仙山森林，以文學、美學、植物學的角度認識森林演替、森林生態，細膩觀察森林中各式各樣的生命力，領人感受森林展現的繽紛姿態。",
    "ActObject": "（一）走讀八仙山森林步道。\r\n（二）藉由繪圖，發現生物細緻的樣貌。\r\n（三）感受八仙山森林環境的豐富。\r\n（四）培養自然美學。\r\n",
    "ActTime": "畫一座森林：111年7月16日，星期六，上午10：10-16：00。夜讀森林：111年7月16日，星期六，下午18：45-21：30。一葉知森：111年7月17，星期日，上午10：10-16：00。",
    "ActHours": null,
    "JoinDesc": "18歲以上成人",
    "JoinFee": "包含入園門票、保險、課程材料費、一份點心與講師費"
    },
    {
    "TYP": "3",
    "AduName": "八仙山自然教育中心",
    "NAduName": "仲夏散冊‧森林畫室",
    "NAduType": "3",
    "onAskStart": "2022/05/04",
    "onAskEnd": "2022/07/03",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=BSS-T1108",
    "ActDesc": "繪圖是人類最早描述知識的途徑之一，相較於文字，圖畫更能直觀地描述與傳達資訊。早期的人們基於各種理由進行繪畫，如：紀錄藥用植物的外觀、紀錄稀有動物的外在特徵、宗教祭祀、賞心悅目、歌功頌德、陶冶性情等，不論細緻程度，都使人更貼近這個世界的真實樣貌，無法搭船遠洋，卻能透過一幅畫看到大海另一端的驚奇奧秘。\r\n繪圖相較攝影，需要耗費更多的時間進行觀察、探究，才能將其特徵或行為精細地描繪，使觀賞者能直觀地接受到描述的事實，透過繪圖也更能引人進入大自然無法言喻的驚喜之處。\r\n八仙山國家森林遊樂區內因過去曾為林場，步道平緩適合沿途觀察，多處平坦開闊草地昔日為宿舍區，現適合就地寫生或素描，因此特規劃八仙山生物繪圖系列課程，以走讀、繪圖的角度進入充滿人文與美學氣質的八仙山森林，以文學、美學、植物學的角度認識森林演替、森林生態，細膩觀察森林中各式各樣的生命力，領人感受森林展現的繽紛姿態。",
    "ActObject": "（一）走讀八仙山森林步道。\r\n（二）藉由繪圖，發現生物細緻的樣貌。\r\n（三）感受八仙山森林環境的豐富。\r\n（四）培養自然美學。\r\n",
    "ActTime": "畫一座森林：111年7月16日，星期六，上午10：10-16：00。夜讀森林：111年7月16日，星期六，下午18：45-21：30。一葉知森：111年7月17，星期日，上午10：10-16：00。",
    "ActHours": null,
    "JoinDesc": "18歲以上成人",
    "JoinFee": "包含入園門票、保險、課程材料費、一份點心與講師費"
    },
    {
    "TYP": "3",
    "AduName": "八仙山自然教育中心",
    "NAduName": "奇獸與牠們的產地－八仙山動物生態探索營",
    "NAduType": "2",
    "onAskStart": "2022/04/24",
    "onAskEnd": "2022/06/22",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=BSS-TA1106",
    "ActDesc": "八仙山一年一度的兒童營，結合孩子們喜愛的卡牌遊戲，將八仙山森林會出現的各種生物，製成獨一無二的「生存之丘牌卡」，每種生物牌卡都有與生物自身習性相關的技能，促使孩子們自發的在森林裡尋找生物，獲得牌卡的同時更認識這個生物，並學習正確觀察生物的方法，感受靠自己翻閱圖鑑及網路查到生物的成就感。\r\n今年度我們加長了活動時間，改成四天三夜，期待孩子們好好享受森林環境的同時，伙伴之間的團隊情誼可以更加深厚，歡迎熱愛自然、想接觸自然的孩子們快快登上奇獸調查團的列車吧！\r\n",
    "ActObject": "(一)\t培養對大自然的觀察力。\r\n(二)\t認識八仙山的生物多樣性。\r\n(三)\t知道八仙山常見的動物種類。\r\n(四)\t建立尊重不同生命的態度。\r\n(五)\t學習團隊合作。\r\n",
    "ActTime": "1.\t活動日期：2022年7月11-14日（星期一至四）\r\n2.\t如遇颱風、不可抗力之因素，則會延期至備用日期：2022年7月25-28日（星期一至四）\r\n",
    "ActHours": null,
    "JoinDesc": "國小4年級-國一（暑假過後就讀年級）",
    "JoinFee": "每人原價7,990元，優惠價7,500元"
    },
    {
    "TYP": "3",
    "AduName": "池南自然教育中心",
    "NAduName": "111年專業成長研習-2：水域活動安全認知與救生操作",
    "NAduType": "3",
    "onAskStart": "2022/05/25",
    "onAskEnd": "2022/06/16",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=CN-T1110",
    "ActDesc": "本研習邀請具有激流救生專長的講師，介紹從事水域活動所需具備的基本觀念、對環境風險的辨識，並加上實地救生技術演練，增進學員從事戶外野地活動的安全認知。\r\n聯絡人：池南自然教育中心　林大成03-864-1594 #15",
    "ActObject": "1.認識基礎的水域活動觀念\r\n2.學習水域環境的風險辨識與管理\r\n3.了解水域救生器材\r\n4.實地練習水域救援操作",
    "ActTime": "2022/6/23(四) 13:30-16:30室內課(池南森林遊樂區)。 2022/6/24(五) 08:30-16:30戶外課(銅門橋水域)。",
    "ActHours": null,
    "JoinDesc": "10名。(含花蓮林管處同仁5名、森林志工等人5名。依報名順序錄取，並視情形調整名額。另備取５名)",
    "JoinFee": "森林志工(請在報名備註欄表明身份)300元、外部人士1000元。現場繳交。詳見簡章。"
    },
    {
    "TYP": "3",
    "AduName": "雙流自然教育中心",
    "NAduName": "鬥陣下水趣",
    "NAduType": "2",
    "onAskStart": "2022/06/11",
    "onAskEnd": "2022/08/24",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=SL-TA1104",
    "ActDesc": "炎熱的夏天是最適合親近溪流與大自然的季節\r\n歡迎來到雙流自然教育中心，享受最清涼的溪流體驗！\r\n\r\n本次活動將帶領大家一起下溪尋找水生生物們，\r\n透過找尋生物的觀察過程，\r\n讓大家一起與溪流零距離接觸，感受沁涼溪水帶來舒服的自然體驗～\r\n並藉著ＤＩＹ手作木頭蜻蜓，帶走課程中的美好記憶與知識！\r\n",
    "ActObject": "１.\t喜歡親近大自然的社會大眾\r\n２.\t對溪流生態觀察有興趣的民眾\r\n３.\t想帶孩子親近溪流的家長",
    "ActTime": "本活動每梯次限額最多35名，額滿為止（若報名人數未滿20位將取消該梯次活動，並全額退費）",
    "ActHours": null,
    "JoinDesc": "（本活動部分課程於水域進行，建議7歲以上孩童參加）",
    "JoinFee": "費用含課程費及DIY材料費，不含門票及停車費，門票及停車費需自行負擔，於入園時由售票口收取"
    },
    {
    "TYP": "3",
    "AduName": "雙流自然教育中心",
    "NAduName": "鬥陣下水趣",
    "NAduType": "2",
    "onAskStart": "2022/06/11",
    "onAskEnd": "2022/08/31",
    "Url": "https://recreation.forest.gov.tw/Education/Course?id=SL-TA1104",
    "ActDesc": "炎熱的夏天是最適合親近溪流與大自然的季節\r\n歡迎來到雙流自然教育中心，享受最清涼的溪流體驗！\r\n\r\n本次活動將帶領大家一起下溪尋找水生生物們，\r\n透過找尋生物的觀察過程，\r\n讓大家一起與溪流零距離接觸，感受沁涼溪水帶來舒服的自然體驗～\r\n並藉著ＤＩＹ手作木頭蜻蜓，帶走課程中的美好記憶與知識！\r\n",
    "ActObject": "１.\t喜歡親近大自然的社會大眾\r\n２.\t對溪流生態觀察有興趣的民眾\r\n３.\t想帶孩子親近溪流的家長",
    "ActTime": "本活動每梯次限額最多35名，額滿為止（若報名人數未滿20位將取消該梯次活動，並全額退費）",
    "ActHours": null,
    "JoinDesc": "（本活動部分課程於水域進行，建議7歲以上孩童參加）",
    "JoinFee": "費用含課程費及DIY材料費，不含門票及停車費，門票及停車費需自行負擔，於入園時由售票口收取"
    }
    ]