export default
[
    {
    "Height": "849-1212",
    "Area": 916.0,
    "FB_URL": "https://www.facebook.com/DYSNEC/",
    "TYP": "3",
    "AduShort": "DYS",
    "AduName": "東眼山自然教育中心",
    "Intro": "在雪山山脈尾稜的柳杉林裡，在真實的環境學習中，創造「人與人」、「人與環境」、「人與社會」之對話。\r\n\r\n東眼山自然教育中心位於東眼山國家森林遊樂區內，屬石門水庫集水區範圍，為雪山山脈西稜之一部份，山形恰似人倒臥的側臉，清晨日出由側臉眼窩的位置升起，因而得名。森林組成兼具整齊優美的人工林及豐富多樣的天然林，還有三千萬年前蝦蟹留下的生痕化石，及其他海相沈積等地質景觀。",
    "Addr": "33643 桃園市復興區霞雲里佳志35號",
    "Phone": "03-3821533",
    "Fax": "03-3821532",
    "Email": "dysnc2007@gmail.com",
    "AdminUnit": "新竹林區管理處",
    "BlogUrl": "http://fable0204.pixnet.net/blog",
    "FBUrl": "https://www.facebook.com/DYSNEC",
    "X": "292208",
    "Y": "2746461",
    "URL": "https://recreation.forest.gov.tw/Education/NC?typ_id=DYS",
    "OpenTime": "平日 08：00 - 17：00     \r\n",
    "Admin_Name": "桃園市復興區"
    },
    {
    "Height": "1100-2600",
    "Area": 2787.0,
    "FB_URL": "https://www.facebook.com/AWDNC",
    "TYP": "3",
    "AduShort": "AWD",
    "AduName": "奧萬大自然教育中心",
    "Intro": "嬉遊在繽紛多彩的松楓林，透過身歷其境的活動，感受自然的脈動，體驗森林多功能價值，了解山林與文明的連結。\r\n\r\n奧萬大自然教育中心位於奧萬大國家森林遊樂區內，全區屬狹谷地形，為多條溪流匯集處，四面環山，「春櫻、夏瀑、秋月、冬楓」四季皆美，且是野生物良好的棲息環境。奧萬大吊橋可遠眺溪谷之美及能高南峰，是園區最佳賞景攬勝之處。",
    "Addr": "54651 南投縣仁愛鄉親愛村大安路153號",
    "Phone": "049-2974499",
    "Fax": "049-2974895",
    "Email": "aowandanc@gmail.com",
    "AdminUnit": "南投林區管理處",
    "BlogUrl": null,
    "FBUrl": "https://www.facebook.com/AWDNC",
    "X": "268221",
    "Y": "2649901",
    "URL": "https://recreation.forest.gov.tw/Education/NC?typ_id=AWD",
    "OpenTime": "上午 8:00～下午17:00 ※當日開放時間以現場公告為準。",
    "Admin_Name": "南投縣仁愛鄉"
    },
    {
    "Height": "140-601",
    "Area": 169.0,
    "FB_URL": "https://www.facebook.com/ChihnanNatureCenter",
    "TYP": "3",
    "AduShort": "CN",
    "AduName": "池南自然教育中心",
    "Intro": "走進洄瀾林業時光森林，體驗低海拔森林山水之美，實踐友善環境生活。\r\n\r\n位於池南國家森林遊樂區內，介於中央山脈與海岸山脈之間的斷層谷地中，鄰近的鯉魚山林相完整，加上鯉魚潭水域環境，孕育豐富動植物生態資源。該區早期是木材生產轉運站，隨處可見過去林木生產的歷史痕跡，感受未曾褪去的林業記憶。",
    "Addr": "974花蓮縣壽豐鄉池南村林園路65號",
    "Phone": "03-8641594分機15",
    "Fax": "03-8641613",
    "Email": "chihnannc@gmail.com",
    "AdminUnit": "花蓮林區管理處",
    "BlogUrl": "https://www.facebook.com/ChihnanNatureCenter/",
    "FBUrl": "https://www.facebook.com/ChihnanNatureCenter",
    "X": "301060",
    "Y": "2646076",
    "URL": "https://recreation.forest.gov.tw/Education/NC?typ_id=CN",
    "OpenTime": "08：00～17：00。當日開放時間以現場公告為準。",
    "Admin_Name": "花蓮縣壽豐鄉"
    },
    {
    "Height": "667-2938",
    "Area": 2492.32,
    "FB_URL": "https://www.facebook.com/BSSNC.tw",
    "TYP": "3",
    "AduShort": "BSS",
    "AduName": "八仙山自然教育中心",
    "Intro": "穿越林場歷史看山、水、林、人的變遷脈絡，深入八仙山體驗蟲、魚、鳥、獸的變幻萬千。\r\n\r\n八仙山國家森林遊樂區早期為八仙山林場，曾與太平山及阿里山林場併稱台灣三大林場。八仙山因主峰海拔2,366公尺，折算為8,000台尺之日文讀音而得名。區內群山環繞，林相多變，加上雨量充沛，孕育出豐富精采的森林資源，貫穿全區的十文溪及佳保溪刻畫出廣闊的河階台地景觀。",
    "Addr": "424台中市和平區東關路一段200之8號",
    "Phone": "04-25950299",
    "Fax": null,
    "Email": "basianshan@gmail.com",
    "AdminUnit": "東勢林區管理處",
    "BlogUrl": "https://www.facebook.com/BSSNC.tw",
    "FBUrl": "https://www.facebook.com/BSSNC.tw",
    "X": "250232",
    "Y": "2677068",
    "URL": "https://recreation.forest.gov.tw/Education/NC?typ_id=BSS",
    "OpenTime": "08:00-17:00",
    "Admin_Name": "台中市和平區"
    },
    {
    "Height": "8-8",
    "Area": 16.0,
    "FB_URL": "https://www.facebook.com/luodong",
    "TYP": "3",
    "AduShort": "LD",
    "AduName": "羅東自然教育中心",
    "Intro": "乘著百年鐵道走進林業文化，踏訪蘭陽青山綠水，我們在城市中與自然一起生活。\r\n\r\n位於羅東林業文化園區內，是早期林產業興盛時期太平山林場的重要轉運中心，日據時期的建築與產業遺址仍保留至今，包含運材火車、鐵道文物、竹林車站等，當時的貯木池如今則化身為生態池，水域與陸域環境構成多樣化的棲地，生物相十分豐富。",
    "Addr": "265宜蘭縣羅東鎮中正北路118號",
    "Phone": "03-9540823",
    "Fax": "03-9532126",
    "Email": "ld.service@eeft.org.tw",
    "AdminUnit": "羅東林區管理處",
    "BlogUrl": "http://luodong-nec.blogspot.tw/",
    "FBUrl": "http://www.facebook.com/luodong",
    "X": "328114",
    "Y": "2730877",
    "URL": "https://recreation.forest.gov.tw/Education/NC?typ_id=LD",
    "OpenTime": "08：00～17：00",
    "Admin_Name": "宜蘭縣羅東鎮"
    },
    {
    "Height": "193-193",
    "Area": 10.0,
    "FB_URL": "https://www.facebook.com/cycknc",
    "TYP": "3",
    "AduShort": "CK",
    "AduName": "觸口自然教育中心",
    "Intro": "接觸淺山生態的窗口，開啟人與林業的對話，實踐友善環境綠生活。\r\n\r\n位於嘉義縣番路鄉省道台18線上，是前往阿里山國家森林遊樂區必經之路，距離嘉義市區僅約20分鐘車程，交通便利。中心所在地為南區樹木銀行，亦為觸口工作站，區內有多棵珍貴老樹、漂流木存放區、生態水道、黃金級綠建築之綠意館等，凸顯人類與自然共處的和諧。",
    "Addr": "602嘉義縣番路鄉新福村1鄰五虎寮18號",
    "Phone": "05-2590211：假日請撥：05-2590004#610",
    "Fax": "05-2594250",
    "Email": "nec5@forest.gov.tw",
    "AdminUnit": "嘉義林區管理處",
    "BlogUrl": null,
    "FBUrl": "https://www.facebook.com/cycknc",
    "X": "204995",
    "Y": "2594534",
    "URL": "https://recreation.forest.gov.tw/Education/NC?typ_id=CK",
    "OpenTime": "09：00～16：30（離園時間下午5:00前） ",
    "Admin_Name": "嘉義縣番路鄉"
    },
    {
    "Height": "150-700",
    "Area": 1584.85,
    "FB_URL": "https://www.facebook.com/SLNC123",
    "TYP": "3",
    "AduShort": "SL",
    "AduName": "雙流自然教育中心",
    "Intro": "穿梭熱帶季風林，順沿溪流訪瀑布，探索生態樂學習，看見土地與人永續共存。\r\n\r\n雙流國家森林遊樂區地處中央山脈與恒春半島之間的山區，內文溪貫穿其間，地形和水域多元的變化，造就兼具熱帶雨林、亞熱帶雨林、熱帶季風雨林、暖溫帶森林之複雜林相及多樣性物種等生態特色。此地亦為排灣族聚落之所在，區內仍可見該原住民族的人文遺蹟。",
    "Addr": "943屏東縣獅子鄉丹路村丹路2巷23號",
    "Phone": "(08)870-1499",
    "Fax": null,
    "Email": "slnc543@gmail.com",
    "AdminUnit": "屏東林區管理處",
    "BlogUrl": null,
    "FBUrl": "https://www.facebook.com/SLNC123",
    "X": "229318",
    "Y": "2457656",
    "URL": "https://recreation.forest.gov.tw/Education/NC?typ_id=SL",
    "OpenTime": "08：00～17：00 ★當日開放以現場公告為主★",
    "Admin_Name": "屏東縣獅子鄉"
    },
    {
    "Height": "125-650",
    "Area": 110.0,
    "FB_URL": "https://www.facebook.com/Jhihbencenter",
    "TYP": "3",
    "AduShort": "JB",
    "AduName": "知本自然教育中心",
    "Intro": "在知本的熱帶季風林裡遇見多樣的文化與自然生態，在溫泉的縷縷輕煙中看見生．活．美．學。\r\n\r\n知本國家森林遊樂區屬熱帶季風氣候，主要代表性植物是榕樹、茄苳及藤本植物，演化出熱帶植物特有的纏勒、絞殺等現象，白榕氣根形成的「千根榕」自然奇景，亦是知本重要的「地標」。區內建築以融入地景為設計原則，同時包容臺東多元民族的文化，呈現自然與人文的融合。",
    "Addr": "954臺東縣卑南鄉溫泉村龍泉路290號",
    "Phone": "089-510961#18(21/22/23)",
    "Fax": "089-510749",
    "Email": "jbcenter089@gmail.com",
    "AdminUnit": "臺東林區管理處",
    "BlogUrl": "https://jbcenter0312.blogspot.com/",
    "FBUrl": "https://www.facebook.com/Jhihbencenter",
    "X": "249191",
    "Y": "2509643",
    "URL": "https://recreation.forest.gov.tw/Education/NC?typ_id=JB",
    "OpenTime": "07:00~17:00 (7、8月份延後1小時休園)",
    "Admin_Name": "台東縣卑南鄉"
    }
    ]
